# -*- coding: utf-8 -*-
"""
生成器：把错误码体系从「253 码」扩展到「生产级（上千个）」。

设计要点（结合 docs/覆盖缺口清单.md）：
- 缺口清单基于 200 码基线，但当前代码已吸收其 P0/P1（现为 253 码）。
- 要真正做到「生产级 / 上千个」，须按真实编译器的完整诊断面新增子系统类别，
  而非仅在 8 大类内小幅加码。本脚本新增 32 个 ErrorCategory 子系统，
  覆盖 宏/特质/所有权/生命周期/泛型/模块/后端/优化器/链接器/ABI/并发/内存/
  LSP/增量/包管理/构建/调试/分布式/插件/目标平台/SIMD/嵌入式/测试/文档/
  Lint/安全/配置/可观测/交叉编译/WASM/GPU。
- 单一数据源（CATALOG）同时生成 4 个必须保持一致的落点：
    ① enum 变体  ② META 条目  ③ code() 匹配臂  ④ all() 列表项
  以及 ErrorCategory 的 4 个落点（枚举变体 + codePrefix/stage/displayName）。
- 插入锚点均唯一，且新前缀（E02..E78）与既有 8 个前缀（E00,E01,E10,E20,E30,E40,E50,E90）无冲突，
  保证 completeness test 的 code.startsWith(cat.codePrefix()) 校验通过。
- 同时产出 vscode-extension/diagnostics-map.json（开发工具映射表），供 VS Code 通用插件消费。
"""
import io
import json
import os
import re

ROOT = r"D:\CodeWorkspace\compiler-diagnostic"
DIAG = os.path.join(ROOT, "src", "diagnostics", "Diagnostics.cj")
TEST = os.path.join(ROOT, "src", "ut", "ErrorCode_test.cj")
VSCODE_DIR = os.path.join(ROOT, "vscode-extension")

# (abbr, prefix, stage, display, [(key, template, fix_or_None, severity), ...])
# variant name = abbr + key（保证全局唯一：各 abbr 互不相同）
CATALOG = [
    ("Macro", "E02", "中端", "Macro（宏系统）", [
        ("UndefinedIdentifier", "宏展开时标识符未定义：{name}", "检查宏参数与导入", "Error"),
        ("ArityMismatch", "宏实参数量不匹配：期望 {expected} 个，得到 {got} 个", "核对宏调用实参", "Error"),
        ("RecursiveExpansion", "宏递归展开未终止（可能的无限展开）", "为宏增加展开边界条件", "Error"),
        ("HygieneViolation", "宏卫生性冲突：捕获了调用方的标识符 {name}", "重命名宏内绑定", "Error"),
        ("InvalidTokenTree", "宏输入不是合法的 token 树", "检查宏输入语法", "Error"),
        ("MissingMacroDef", "未找到宏定义：{name}", "导入或定义该宏", "Error"),
        ("DuplicateMacroDef", "宏 {name} 被重复定义", "删除重复定义", "Error"),
        ("WrongFragmentKind", "宏片段类型不匹配（expr/stmt/ty/item）", "使用正确的片段说明符", "Error"),
        ("MetavarReuse", "同一元变量在宏规则中被重复绑定：{name}", "重命名元变量", "Error"),
        ("NoMatchingRule", "没有任何宏规则匹配输入", "调整输入或新增宏规则", "Error"),
        ("ReservedName", "宏使用了保留的元变量名：{name}", "改用非保留名", "Error"),
        ("ContextualKeyword", "宏内出现上下文关键字误用：{kw}", "检查关键字上下文", "Error"),
        ("ExpansionDepthLimit", "宏展开深度超过上限（{limit}）", "简化嵌套宏调用", "Error"),
        ("MalformedAttribute", "属性宏参数格式非法", "检查属性宏参数", "Error"),
        ("DeriveConflict", "derive 宏生成代码与手写代码冲突：{trait}", "移除冲突实现", "Error"),
        ("ProcMacroPanic", "过程宏执行异常终止", "修复过程宏实现", "Error"),
        ("ProcMacroTimeout", "过程宏执行超时", "优化过程宏性能", "Error"),
        ("ProcMacroIOError", "过程宏访问文件系统失败", "避免过程宏做 IO", "Error"),
        ("QuoteSpanLost", "quote! 生成的代码丢失源码位置", "使用 span 传递", "Warning"),
        ("RuleAmbiguity", "宏规则存在歧义，多处可匹配", "细化宏规则优先级", "Warning"),
        ("EmptyRepetition", "宏重复匹配为空但要求至少一次", "检查重复分隔符", "Error"),
        ("SeparatorMismatch", "宏重复分隔符不匹配：期望 {sep}", "使用正确分隔符", "Error"),
        ("TTNotBalance", "宏 token 树括号不平衡", "补全括号", "Error"),
        ("UnresolvedFragment", "宏片段引用的外部符号未解析：{name}", "导入对应符号", "Error"),
        ("BuiltinMacroUnsupported", "内建宏在当前目标不支持：{name}", "改用等价实现", "Error"),
        ("MacroInConst", "在常量上下文使用非常量宏", "改用在运行时求值", "Error"),
        ("CfgMacroBranch", "cfg 宏分支全部被禁用，无可用分支", "检查 cfg 条件", "Warning"),
        ("DocMacroBroken", "文档宏（如 html_root_url）参数非法", "修正文档宏参数", "Warning"),
        ("FormatMacroParse", "format! 宏格式串解析失败：{spec}", "检查占位符与参数", "Error"),
        ("LogMacroLevel", "日志宏级别非法：{level}", "使用合法日志级别", "Error"),
        ("AssertMacroMsg", "assert! 宏消息参数类型非法", "消息须为字符串或格式化串", "Error"),
        ("VecMacroNonUniform", "vec! 宏元素类型不一致", "统一元素类型", "Error"),
        ("IncludeMacroFail", "include! 宏读取文件失败：{path}", "检查文件路径与权限", "Error"),
        ("ConcatMacroType", "concat! 宏拼接结果类型非法", "确保拼接为合法字面量", "Error"),
        ("EnvMacroMissing", "env! 宏读取的环境变量不存在：{var}", "设置环境变量", "Error"),
        ("SelectMacroConflict", "select! 宏分支模式冲突", "统一分支类型", "Error"),
        ("MacroDefRecursion", "宏定义本身递归引用自身", "断开宏定义循环", "Error"),
        ("GenericMacroParam", "泛型宏参数未推导：{name}", "补充类型标注", "Error"),
        ("UnsafeMacroExpansion", "宏展开产生了不安全的代码但缺少 unsafe 块", "添加 unsafe 块", "Error"),
        ("MacroSpanOverflow", "宏展开生成的源码跨度超过编译器限制", "拆分宏生成代码", "Warning"),
    ]),
    ("Trait", "E03", "中端", "Trait（特质/接口）", [
        ("MethodNotImplemented", "trait {trait} 的方法 {method} 未实现", "补全缺失的 trait 方法", "Error"),
        ("MethodSignatureMismatch", "trait 方法 {method} 的实现签名不匹配", "对齐参数与返回类型", "Error"),
        ("MissingSupertrait", "缺少父 trait {super} 的实现", "实现父 trait", "Error"),
        ("ConflictingImpl", "为同一类型实现了冲突的 trait {trait}", "移除其中一个实现", "Error"),
        ("OrphanRuleViolation", "实现违反了孤儿规则（类型与 trait 均非本地）", "将实现移到定义侧", "Error"),
        ("NegativeImplConflict", "否定实现与正向实现冲突：{trait}", "移除冲突实现", "Error"),
        ("SealedTraitLeak", "试图在 crate 外实现封闭 trait {trait}", "仅在 crate 内实现", "Error"),
        ("AssociatedTypeMissing", "trait {trait} 的关联类型 {assoc} 未指定", "提供关联类型", "Error"),
        ("AssociatedTypeBound", "关联类型不满足 bound：{bound}", "调整关联类型约束", "Error"),
        ("DefaultImplConflict", "默认实现与具体实现冲突：{method}", "移除重复实现", "Error"),
        ("MarkerTraitMisuse", "标记 trait {trait} 不应有方法体", "改为纯标记 trait", "Error"),
        ("DynTraitNotObjectSafe", "trait {trait} 不是对象安全的，不能用于 dyn", "移除不安全的成员", "Error"),
        ("DynTraitGeneric", "泛型 trait 不能直接用于 dyn（需指定实参）", "提供泛型实参", "Error"),
        ("TraitBoundUnmet", "类型 {ty} 不满足 trait bound {trait}", "为类型实现该 trait", "Error"),
        ("HigherRankedBound", "高阶 trait bound 推导失败", "显式标注生命周期", "Error"),
        ("TraitAliasCycle", "trait 别名存在循环引用", "打破别名循环", "Error"),
        ("ImplForBoundParam", "不能对泛型 bound 参数直接 impl trait", "改用具体类型", "Error"),
        ("SpecializationFailure", "特化实现冲突（更具体的实现未生效）", "检查特化层级", "Error"),
        ("AutoTraitNotImpl", "自动 trait {trait} 未能自动推导", "检查含非自动字段", "Error"),
        ("AutoTraitConflict", "自动 trait 推导与显式实现冲突", "统一实现策略", "Error"),
        ("CoordTraitAmbig", "联动 trait（coherence）判定歧义", "明确实现归属", "Error"),
        ("UnsafeTraitImpl", "不安全 trait 实现缺少 unsafe 标注", "添加 unsafe 实现块", "Error"),
        ("TraitMethodVisibility", "trait 方法可见性低于实现要求", "提升方法可见性", "Error"),
        ("WhereClauseOnImpl", "impl 块的 where 子句不满足", "补全 where 约束", "Error"),
        ("BlanketImplConflict", " blanket 实现与其他实现冲突", "缩小 blanket 范围", "Error"),
        ("TraitObjectCovariance", "trait 对象协变非法", "使用不变类型参数", "Error"),
        ("AssocTypeProjection", "关联类型投影失败：{assoc}", "检查类型投影路径", "Error"),
        ("TraitMethodDefaultParam", "trait 方法含默认参数但不被支持", "改用重载或 option", "Error"),
        ("AsyncTraitNotSupported", "当前不支持 async trait 方法 {method}", "改用返回 Future 的同步签名", "Error"),
        ("TraitMethodGenericClash", "trait 方法泛型与实现泛型冲突", "对齐泛型参数", "Error"),
        ("DuplicateAssocConst", "关联常量 {name} 被重复定义", "删除重复定义", "Error"),
        ("AssocConstType", "关联常量类型不匹配：期望 {expected}", "统一关联常量类型", "Error"),
        ("TraitMethodByName", "按名取 trait 方法失败：{method}", "检查方法可见性", "Error"),
        ("ImplGenericCount", "impl 的泛型参数数量不匹配", "核对泛型实参", "Error"),
        ("TraitRequirementCycle", "trait 需求形成循环依赖", "打破循环依赖", "Error"),
        ("DispatchResolution", "trait 方法静态/动态分发解析失败", "显式指定分发方式", "Error"),
        ("TraitMethodOverride", "试图重写非虚 trait 方法", "使用 virtual 方法", "Error"),
        ("LateBoundParam", "晚绑定参数在 impl 中无法确定", "提供具体类型", "Error"),
        ("TraitInheritanceDepth", "trait 继承层级过深", "扁平化 trait 层级", "Warning"),
        ("SelfImplConflict", "为 Self 类型实现自身 trait 冲突", "调整实现类型", "Error"),
    ]),
    ("Borrow", "E04", "中端", "Borrow（所有权/借用）", [
        ("MoveOutOfBorrowed", "从已借用的值中移动：{name}", "先结束借用再移动", "Error"),
        ("BorrowAfterMove", "在值被移动后继续借用：{name}", "调整借用顺序", "Error"),
        ("MutableBorrowConflict", "存在可变借用时又产生其他借用", "确保同一时刻仅一种借用", "Error"),
        ("AliasingMutableBorrow", "存在多个可变别名借用", "使用单一可变引用", "Error"),
        ("BorrowEscapesScope", "借用逃出其生命周期范围：{name}", "缩短借用或延长所有者", "Error"),
        ("UseOfMovedValue", "使用了已被移动的值：{name}", "在使用前克隆或避免移动", "Error"),
        ("PartialMoveStruct", "对结构体部分字段移动后整体不可用", "移动前完成所需访问", "Error"),
        ("MoveInMatchGuard", "在 match guard 中移动值导致后续不可用", "改用引用匹配", "Error"),
        ("ClosureCaptureByMove", "闭包按值捕获了被借用的变量", "改用引用捕获", "Error"),
        ("ReturnReferenceToLocal", "返回了对局部变量的引用", "返回拥有的值或延长生命周期", "Error"),
        ("TemporaryLifetime", "临时值生命周期不足：{name}", "绑定到具名变量", "Error"),
        ("BorrowOfMovedField", "借用了已被移动的结构体字段", "避免部分移动", "Error"),
        ("SelfBorrowInMethod", "方法中对 self 同时发生可变与不可变借用", "拆分方法调用", "Error"),
        ("ReborrowFailed", "重新借用失败：{name}", "调整借用来源", "Error"),
        ("CopyTraitMissing", "期望类型可 Copy 但实际未实现 Copy", "为类型实现 Copy 或改用引用", "Error"),
        ("DropDuringBorrow", "在借用期间显式 drop 导致悬垂", "结束借用后再 drop", "Error"),
        ("BorrowInMatchArm", "match 臂中借用与移动冲突", "统一臂内使用方式", "Error"),
        ("DoubleMutableBorrow", "对同一值两次可变借用", "复用同一可变引用", "Error"),
        ("ImmutableToMutable", "由不可变借用派生了可变借用", "从源头使用可变借用", "Error"),
        ("BorrowInClosureArg", "闭包参数借用与调用方借用冲突", "调整闭包签名", "Error"),
        ("UnsafeBypassBorrow", "unsafe 代码绕过了借用检查但不安全", "审查 unsafe 借用", "Warning"),
        ("PhantomBorrow", "PhantomData 导致意外的借用约束", "调整 PhantomData 参数", "Warning"),
        ("BorrowInLoop", "循环中借用随迭代失效", "将借用移出循环体", "Error"),
        ("FieldBorrowEscape", "字段借用逃逸出包含结构体的生命周期", "缩短字段借用", "Error"),
        ("GenericBorrowBound", "泛型借用约束无法满足", "放宽或显式标注借用", "Error"),
        ("MoveAcrossAwait", "在 await 点移动了非 Send 值", "确保跨 await 的值可 Send", "Error"),
        ("BorrowOfDropType", "借用包含 Drop 实现的类型导致约束冲突", "调整借用范围", "Error"),
        ("ReturnBorrowedParam", "返回的借用与参数生命周期不匹配", "使用生命周期参数关联", "Error"),
        ("SelfReferential", "检测到自引用结构（借用自身字段）", "使用 heap 间接或重构", "Error"),
        ("AsyncMoveCapture", "async 块按移动捕获了被借用的变量", "改用 Arc/引用", "Error"),
        ("BorrowInMatchGuard2", "match guard 借用与主体借用冲突", "合并借用作用域", "Error"),
        ("StaticBorrowViolation", "静态变量借用违反初始化顺序", "改用 lazy 初始化", "Error"),
        ("InteriorMutRace", "内部可变性在借用检查下仍竞争", "使用同步内部可变类型", "Error"),
        ("BorrowOfUnsized", "尝试借用未定长（unsized）类型", "使用指针或定长容器", "Error"),
        ("ScopedBorrowEnd", "借用结束点推断错误导致提前释放", "显式绑定借用", "Error"),
        ("MoveInClosure", "闭包内移动了外部仍需使用的值", "克隆或改用引用", "Error"),
        ("BorrowInMatchGuard3", "guard 与 arm 对同一值的不同借用", "统一借用模式", "Error"),
        ("TemporaryBorrowDrop", "临时借用在语句结束前被丢弃", "绑定到具名变量", "Error"),
        ("TraitObjectBorrow", "trait 对象借用约束无法满足", "使用具体类型或泛型", "Error"),
        ("CoerceBorrowMismatch", "借用强制转换（&T -> &U）失败", "检查类型可转换性", "Error"),
    ]),
    ("Lifetime", "E05", "中端", "Lifetime（生命周期）", [
        ("UnboundedLifetime", "生命周期参数缺少约束（可能为 'static 误用）", "添加生命周期 bound", "Error"),
        ("LifetimeMismatch", "生命周期 {a} 与 {b} 不匹配", "统一生命周期标注", "Error"),
        ("MissingLifetime", "引用返回缺少生命周期标注", "为引用添加生命周期参数", "Error"),
        ("AnonymousLifetimeConflict", "匿名生命周期推断冲突", "显式标注生命周期", "Error"),
        ("StaticRequirements", "期望 'static 但实际生命周期更短", "延长生命周期或使用 'static", "Error"),
        ("LifetimeInTypeAlias", "类型别名中的生命周期未绑定", "在别名处标注生命周期", "Error"),
        ("VarianceViolation", "生命周期型变（variance）非法", "调整型变标注", "Error"),
        ("HigherRankedLifetime", "高阶生命周期（for<'a>）推导失败", "显式标注 for<'a>", "Error"),
        ("LifetimeElisionFail", "生命周期省略规则无法应用", "手动标注生命周期", "Error"),
        ("StructFieldLifetime", "结构体字段生命周期约束不一致", "统一字段生命周期", "Error"),
        ("BorrowLifetimeShort", "借用的生命周期短于使用者", "延长所有者生命周期", "Error"),
        ("OutlivesFailure", "生命周期 {a} 未超出（outlive）{b}", "调整生命周期关系", "Error"),
        ("PhantomLifetime", "PhantomData 生命周期参数冗余或缺失", "校正 PhantomData 标注", "Warning"),
        ("AsyncLifetimeCapture", "async 块捕获了短生命周期引用", "避免捕获短生命周期", "Error"),
        ("ClosureLifetimeCapture", "闭包捕获的引用生命周期不足", "延长被捕获引用", "Error"),
        ("IteratorLifetime", "迭代器关联生命周期不匹配", "检查 Item 生命周期", "Error"),
        ("TraitObjectLifetime", "trait 对象默认生命周期推断错误", "显式指定 + 'a 或 'static", "Error"),
        ("ReturnRefLifetime", "返回的引用生命周期无法关联参数", "使用输入生命周期参数", "Error"),
        ("SelfLifetime", "impl 中 Self 的生命周期约束冲突", "调整 impl 生命周期", "Error"),
        ("GenericLifetimeBound", "泛型生命周期 bound 无法满足", "放宽 bound", "Error"),
        ("CovariantReturnLifetime", "协变返回类型生命周期不兼容", "使用不变生命周期", "Error"),
        ("LifetimeInImplTrait", "impl Trait 中的生命周期约束失败", "显式标注隐藏类型生命周期", "Error"),
        ("NestedLifetime", "嵌套生命周期推断循环", "手动标注内层生命周期", "Error"),
        ("StaticRefCapture", "捕获了 'static 但要求更短生命周期", "改为短生命周期引用", "Error"),
        ("DropLifetime", "Drop 实现中生命周期约束冲突", "简化 Drop 逻辑", "Error"),
        ("LifetimeSubtyping", "子类型生命周期关系不成立", "调整生命周期层级", "Error"),
        ("EarlyBoundLateBound", "早绑定与晚绑定生命周期混用错误", "统一绑定时机", "Error"),
        ("LifetimeInConst", "const 上下文中生命周期标注无效", "移除 const 中的生命周期", "Error"),
        ("YieldLifetime", "生成器（yield）生命周期不一致", "统一生成器生命周期", "Error"),
        ("BorrowSplitLifetime", "拆分借用导致生命周期分裂", "使用单一借用", "Error"),
        ("FunctionPointerLifetime", "函数指针引用生命周期不匹配", "检查函数签名生命周期", "Error"),
        ("ArrayLifetime", "数组元素引用生命周期冲突", "统一元素生命周期", "Error"),
        ("UnionLifetime", "联合体字段引用生命周期不安全", "避免在 union 中使用引用", "Error"),
        ("TraitMethodLifetime", "trait 方法生命周期与实现不一致", "对齐生命周期标注", "Error"),
        ("LifetimeNameConflict", "生命周期参数名 {name} 重复", "重命名生命周期参数", "Error"),
        ("RAIILifetime", "RAII 资源生命周期过早结束", "延长资源所有者", "Error"),
        ("GenericAssocLifetime", "关联类型生命周期 bound 失败", "添加关联类型生命周期", "Error"),
        ("ReferenceToTempLifetime", "对临时值的引用生命周期不足", "绑定到具名变量", "Error"),
        ("LifetimeOnTrait", "trait 自身生命周期参数使用非法", "移除或修正 trait 生命周期", "Error"),
    ]),
    ("Generic", "E06", "中端", "Generic（泛型）", [
        ("ArgumentCountMismatch", "泛型实参数量不匹配：期望 {expected}，得到 {got}", "核对泛型实参", "Error"),
        ("TypeArgumentInference", "泛型类型实参无法推导", "显式标注泛型实参", "Error"),
        ("ConstraintViolation", "泛型约束不满足：{bound}", "满足泛型约束", "Error"),
        ("MissingTraitBound", "泛型类型缺少 trait bound {trait}", "为泛型添加 bound", "Error"),
        ("RecursiveAlias", "泛型别名存在递归且无大小", "打破别名递归", "Error"),
        ("MonomorphizationFailed", "泛型单态化失败：{name}", "检查泛型实参是否可实例化", "Error"),
        ("CodeBloatLimit", "单态化生成代码量超过限制（{limit}）", "减少泛型实例化组合", "Error"),
        ("HigherRankedBound", "高阶泛型 bound 推导失败", "显式标注 bound", "Error"),
        ("DefaultArgumentMissing", "泛型默认实参缺失", "提供默认实参或显式指定", "Error"),
        ("DefaultArgumentConflict", "泛型默认实参与显式实参冲突", "统一实参来源", "Error"),
        ("VarianceMismatch", "泛型型变标注与用法冲突", "调整型变标注", "Error"),
        ("UnsizedGeneric", "泛型参数要求定长但传入未定长类型", "添加 Sized bound", "Error"),
        ("AssociatedTypeUnbound", "泛型关联类型未绑定", "指定关联类型", "Error"),
        ("GATNotSupported", "当前不支持泛型关联类型（GAT）", "改用具体关联类型", "Error"),
        ("ConstGenericMismatch", "常量泛型实参不匹配：期望 {expected}", "核对常量泛型值", "Error"),
        ("ConstGenericNonConst", "常量泛型实参不是编译期常量", "使用编译期常量", "Error"),
        ("ConstGenericOverflow", "常量泛型求值溢出", "降低常量值", "Error"),
        ("TraitObjectGeneric", "泛型 trait 对象无法直接构建", "指定泛型实参", "Error"),
        ("ImplGenericConflict", "泛型 impl 与具体 impl 冲突", "移除冲突实现", "Error"),
        ("BlanketImplConflict", "泛型 blanket 实现与具体实现冲突", "缩小 blanket 范围", "Error"),
        ("GenericMethodResolution", "泛型方法重载解析失败", "显式指定泛型实参", "Error"),
        ("TypeParamShadow", "泛型类型参数 {name} 被遮蔽", "重命名类型参数", "Error"),
        ("GenericInEnum", "枚举泛型约束无法满足", "放宽枚举泛型 bound", "Error"),
        ("GenericFunctionPointer", "泛型函数指针类型不兼容", "对齐泛型签名", "Error"),
        ("SpecializationFailed", "泛型特化实现未生效", "检查特化层级", "Error"),
        ("PhantomTypeMismatch", "PhantomData 泛型参数不匹配", "校正 PhantomData 类型", "Error"),
        ("WhereClauseUnmet", "where 子句约束未满足", "补全 where 约束", "Error"),
        ("TypeParamCountInImpl", "impl 泛型参数数量不一致", "核对泛型参数", "Error"),
        ("GenericAliasCycle", "泛型类型别名循环引用", "打破别名循环", "Error"),
        ("NegativeImplAmbig", "否定实现与泛型实现歧义", "明确实现边界", "Error"),
        ("GenericStructField", "结构体泛型字段约束冲突", "统一字段泛型 bound", "Error"),
        ("HigherRankedInType", "类型内高阶泛型推导失败", "显式标注泛型", "Error"),
        ("GenericTraitBound", "泛型 trait bound 多重冲突", "精简 trait bound", "Error"),
        ("ExistentialGeneric", "存在类型泛型标注非法", "修正存在类型", "Error"),
        ("GenericDefaultCycle", "泛型默认实参形成循环", "打破默认实参循环", "Error"),
        ("UnsoundGeneric", "泛型实现存在不健全（unsound）风险", "审查泛型约束", "Warning"),
        ("GenericCoherence", "泛型实现的连贯性（coherence）判定失败", "明确实现归属", "Error"),
        ("TupleGenericMismatch", "元组泛型元素类型不匹配", "统一元组元素类型", "Error"),
        ("ArrayGenericLen", "数组泛型长度不匹配：期望 {expected}", "核对数组长度", "Error"),
        ("ImplTraitPosition", "impl Trait 位置不支持（仅允许参数/返回）", "调整 impl Trait 位置", "Error"),
        ("GenericInlineCycle", "泛型内联展开形成循环", "打破内联循环", "Error"),
    ]),
    ("Module", "E07", "中端", "Module（模块系统）", [
        ("ModuleNotFound", "模块 {module} 未找到", "检查模块路径或创建模块", "Error"),
        ("FileNotFound", "模块文件 {file} 不存在", "创建对应源文件", "Error"),
        ("CyclicModule", "模块依赖存在循环", "打破模块循环依赖", "Error"),
        ("DuplicateModule", "模块 {module} 被重复定义", "删除重复模块声明", "Error"),
        ("VisibilityViolation", "模块内私有项被跨模块访问：{name}", "调整可见性", "Error"),
        ("ReexportConflict", "重导出（pub use）冲突：{name}", "移除冲突重导出", "Error"),
        ("GlobConflict", "通配重导出（pub use *）引入歧义", "改用显式重导出", "Warning"),
        ("WrongModuleTree", "声明位置与模块树结构不符", "调整文件/目录结构", "Error"),
        ("AnonymousModule", "匿名模块（目录无 mod 声明）无法解析", "为目录添加 mod 声明", "Error"),
        ("ModuleNameConflict", "模块名与已有项冲突：{name}", "重命名模块", "Error"),
        ("NestedModuleDepth", "模块嵌套层级过深（{depth}）", "扁平化模块结构", "Warning"),
        ("MacroUseScope", "宏可见性作用域不足（需 #[macro_use]）", "调整宏导出作用域", "Error"),
        ("PathResolution", "路径 {path} 无法解析", "检查路径拼写与导入", "Error"),
        ("SuperOutside", "super 路径指向模块树根之外", "修正 super 使用位置", "Error"),
        ("CrateRootMissing", "crate 根模块缺失", "添加 lib/main 入口", "Error"),
        ("InlineModuleConflict", "内联模块与文件模块定义冲突", "统一模块定义方式", "Error"),
        ("ExternalCrateNotFound", "外部 crate {crate} 未声明依赖", "在配置中添加依赖", "Error"),
        ("ExternalCrateVersion", "外部 crate 版本不满足：期望 {expected}", "调整依赖版本", "Error"),
        ("FeatureGateModule", "模块需特性开关（feature）但未开启", "开启对应特性", "Error"),
        ("PrivateModuleLeak", "私有模块被公开重导出", "移除公开重导出", "Error"),
        ("ModuleInitOrder", "模块初始化顺序未定义", "显式初始化顺序", "Error"),
        ("CfgModuleDisabled", "cfg 禁用的模块被引用", "检查 cfg 条件", "Error"),
        ("AmbiguousPath", "路径 {path} 存在多个候选", "使用完全限定路径", "Error"),
        ("UseAsConflict", "use 别名与本地定义冲突：{name}", "重命名别名", "Error"),
        ("TraitInModule", "trait 在模块中未正确导出", "添加 pub 导出", "Error"),
        ("StructInModule", "结构体在模块中不可见：{name}", "提升可见性", "Error"),
        ("EnumVariantPath", "枚举变体路径解析失败：{path}", "检查枚举路径", "Error"),
        ("ModuleDocConflict", "模块文档与目录文档冲突", "统一模块文档", "Warning"),
        ("UnsafeModuleExport", "模块导出不安全项但缺少 unsafe", "添加 unsafe 标注", "Error"),
        ("GenericModuleParam", "泛型模块参数未推导", "显式标注泛型", "Error"),
        ("PlatformModule", "平台特定模块在当前目标不可用", "检查目标条件编译", "Error"),
        ("TestModuleLeak", "测试模块（test）被发布构建引用", "限定到 test cfg", "Error"),
        ("BenchModule", "基准测试模块引用错误", "检查 bench 配置", "Error"),
        ("MacroModuleSep", "声明宏与作用域模块分离导致失效", "合并宏作用域", "Error"),
        ("ModuleCyclicReexport", "模块重导出形成循环", "打破重导出循环", "Error"),
        ("HiddenModule", "模块因可见性被完全隐藏", "调整可见性层级", "Error"),
        ("ModuleAttrConflict", "模块属性（attr）相互冲突", "移除冲突属性", "Error"),
        ("NamespaceConflict", "类型与值命名空间冲突：{name}", "重命名冲突项", "Error"),
        ("InlineInFile", "内联模块定义在非预期文件", "调整模块位置", "Error"),
        ("EmptyModule", "模块无任何导出项", "补充模块内容或移除", "Warning"),
    ]),
    ("Backend", "E11", "后端", "Backend（后端/LLVM）", [
        ("LlvmVerifyFailed", "LLVM 模块校验失败：{pass}", "检查生成的中间表示", "Error"),
        ("LlvmLoweringFailed", "LLVM IR 降级失败：{reason}", "检查前端生成代码", "Error"),
        ("LlvmOptCrash", "LLVM 优化器崩溃", "禁用该优化 pass 或升级工具链", "Error"),
        ("LlvmUnsupported", "LLVM 不支持该特性：{feature}", "改用受支持的实现", "Error"),
        ("IrInvalid", "生成的中间表示（IR）非法：{reason}", "检查前端代码生成", "Error"),
        ("IrTypeMismatch", "IR 类型不匹配：期望 {expected}", "统一 IR 类型", "Error"),
        ("IrMissingDef", "IR 中引用了未定义的符号 {name}", "补全符号定义", "Error"),
        ("IrUnreachable", "IR 包含不可达基本块未清理", "清理死代码", "Warning"),
        ("RegisterAllocFailed", "寄存器分配失败（寄存器不足）", "减少局部变量或拆分函数", "Error"),
        ("StackFrameTooLarge", "栈帧过大（{size} 字节）", "减少栈上大对象", "Error"),
        ("CodeLayoutFailed", "代码布局（code layout）失败", "调整函数布局策略", "Warning"),
        ("SectionEmitFailed", "目标段（section）写入失败", "检查段属性", "Error"),
        ("RelocationUnsupported", "目标不支持该重定位类型", "更换目标或调整代码", "Error"),
        ("TargetFeatureAbsent", "目标特性 {feature} 不可用", "启用目标特性", "Error"),
        ("CallingConvUnknown", "未知的调用约定：{conv}", "使用受支持的调用约定", "Error"),
        ("DebugInfoLost", "调试信息在后端丢失", "保留调试信息生成", "Warning"),
        ("EhTableTooLarge", "异常处理表过大", "拆分函数或减少异常路径", "Error"),
        ("GlobalInitFailed", "全局变量初始化失败", "检查全局初始化表达式", "Error"),
        ("ConstantFoldBackend", "后端常量折叠失败", "简化常量表达式", "Error"),
        ("AsmEmitFailed", "内联汇编生成失败：{reason}", "检查汇编语法", "Error"),
        ("VectorBackend", "向量指令后端生成失败", "改用标量实现", "Error"),
        ("TailCallUnsupported", "目标不支持尾调用优化", "避免尾调用", "Warning"),
        ("InlineAsmConstraint", "内联汇编约束（constraint）非法", "修正约束字符串", "Error"),
        ("MetadataEmit", "LLVM 元数据写入失败", "检查元数据格式", "Error"),
        ("ModuleParse", "LLVM 位码（bitcode）解析失败", "重新生成位码", "Error"),
        ("TargetMachineInit", "目标机器（TargetMachine）初始化失败", "检查目标三元组", "Error"),
        ("DataLayoutMismatch", "数据布局（datalayout）不匹配", "统一数据布局", "Error"),
        ("ABILowering", "ABI 降级（lowering）失败", "检查函数签名 ABI", "Error"),
        ("UnwindInfoFailed", "展开信息（unwind）生成失败", "检查异常处理配置", "Error"),
        ("ProfileInstrument", "性能分析插桩失败", "关闭插桩或调整配置", "Warning"),
        ("SanitizerUnsupported", "该目标不支持消毒剂（sanitizer）", "更换目标或关闭 sanitizer", "Error"),
        ("ThinLtoFailed", "ThinLTO 失败", "改用完整 LTO 或禁用", "Warning"),
        ("LtoModuleConflict", "LTO 跨模块符号冲突", "统一符号定义", "Error"),
        ("BackendTimeout", "后端处理超时", "简化函数或增加超时", "Error"),
        ("BackendOOM", "后端内存耗尽", "减少编译单元规模", "Error"),
        ("VerifierLimit", "LLVM 校验器超过内部限制", "拆分模块", "Warning"),
        ("IntrinsicLowering", "内建函数（intrinsic）降级失败：{name}", "检查 intrinsic 签名", "Error"),
        ("BlockAddressInvalid", "块地址（blockaddress）引用非法", "修正块引用", "Error"),
        ("ComdatFailed", "COMDAT 分组失败", "检查 comdat 选择", "Error"),
        ("AliasEmitFailed", "别名（alias）生成失败", "检查别名目标", "Error"),
        ("WeakSymbolConflict", "弱符号（weak）冲突", "统一符号强弱", "Error"),
    ]),
    ("Opt", "E12", "后端", "Optimizer（优化器）", [
        ("PassFailed", "优化 pass {pass} 执行失败", "禁用该 pass 或报告工具链 bug", "Error"),
        ("PassCrashed", "优化器在 pass {pass} 崩溃", "升级工具链或绕过该 pass", "Error"),
        ("Invalidation", "优化后的 IR 与前置约束冲突", "检查优化合法性", "Error"),
        ("LoopUnrollFailed", "循环展开失败", "调整循环边界或禁用展开", "Warning"),
        ("VectorizationFailed", "向量化失败", "改用手写标量循环", "Warning"),
        ("InliningFailed", "函数内联失败：{reason}", "调整内联阈值", "Warning"),
        ("InliningTooDeep", "内联递归过深", "限制内联深度", "Warning"),
        ("DeadCodeNotRemoved", "死代码未被移除（可能的 bug）", "检查优化级别", "Warning"),
        ("ConstPropOverflow", "常量传播溢出", "降低常量规模", "Error"),
        ("GvnConflict", "全局值编号（GVN）冲突", "检查表达式等价性", "Error"),
        ("SccpFailed", "稀疏条件常量传播失败", "简化控制流", "Error"),
        ("Mem2RegFailed", "内存到寄存器提升失败", "检查内存访问模式", "Error"),
        ("LoopInvariantFailed", "循环不变量外提失败", "调整循环结构", "Warning"),
        ("TailDuplicateFailed", "尾块复制失败", "调整控制流", "Warning"),
        ("PeepholeFailed", "窥孔优化失败", "检查指令序列", "Error"),
        ("StrengthReduction", "强度削减产生非法序列", "检查运算等价性", "Error"),
        ("AliasAnalysisFailed", "别名分析失败", "放宽别名假设", "Warning"),
        ("OptLevelInvalid", "优化级别非法：{level}", "使用合法优化级别", "Error"),
        ("OptSizeConflict", "优化尺寸（Os/Oz）与速度冲突", "统一优化目标", "Warning"),
        ("ProfileMismatch", "优化使用的性能画像不匹配", "重新采集画像", "Warning"),
        ("OptCorruptIr", "优化破坏了 IR 合法性", "报告工具链 bug", "Error"),
        ("LoopRotateFailed", "循环旋转失败", "调整循环条件", "Warning"),
        ("GlobalOptFailed", "全局优化失败", "检查全局变量初始化", "Error"),
        ("IpConstantProp", "过程间常量传播失败", "简化调用图", "Warning"),
        ("ArgumentPromotion", "参数提升优化失败", "检查参数类型", "Error"),
        ("StructRetOpt", "结构体返回优化失败", "调整返回类型", "Warning"),
        ("TailCallOptFailed", "尾调用优化失败", "检查尾调用形态", "Warning"),
        ("SLPVectorizeFailed", "SLP 向量化失败", "放宽向量化条件", "Warning"),
        ("LoopVersioning", "循环版本化失败", "禁用循环版本化", "Warning"),
        ("PartialInline", "部分内联失败", "关闭部分内联", "Warning"),
        ("HotColdSplit", "冷热代码分离失败", "关闭该优化", "Warning"),
        ("MergeFuncFailed", "函数合并优化失败", "检查函数签名等价", "Error"),
        ("GVNLoadElim", "负载消除（load elim）冲突", "检查内存模型", "Error"),
        ("OptzLoopUnswitch", "循环外提（unswitch）失败", "调整条件", "Warning"),
        ("ReassociateFailed", "表达式重结合失败", "检查结合律合法性", "Error"),
        ("OptLoopIdiom", "循环惯用法识别失败", "关闭惯用法优化", "Warning"),
        ("CFGSimplifyFailed", "控制流图简化失败", "检查异常边", "Warning"),
        ("OptIndVar", "归纳变量优化失败", "调整循环变量", "Warning"),
        ("DivRemOpt", "除/余优化产生未定义行为", "检查除零", "Error"),
        ("OptShiftBase", "移位优化溢出", "检查移位量", "Error"),
        ("OptFloatReassoc", "浮点重结合改变语义", "关闭浮点重结合", "Warning"),
    ]),
    ("Linker", "E13", "后端", "Linker（链接器）", [
        ("LinkerNotFound", "未找到链接器（linker）", "安装或配置链接器路径", "Error"),
        ("LinkerInvocation", "链接器调用失败：{reason}", "检查链接命令与参数", "Error"),
        ("UndefinedSymbol", "链接时未定义符号：{symbol}", "补充该符号的定义或依赖", "Error"),
        ("DuplicateSymbol", "链接时符号重复定义：{symbol}", "移除重复定义", "Error"),
        ("LibraryNotFound", "链接库 {lib} 未找到", "检查库路径（-L）", "Error"),
        ("LibraryVersion", "链接库版本不兼容：{lib}", "升级或降级依赖库", "Error"),
        ("MissingEntryPoint", "缺少入口符号（如 main）", "提供入口函数", "Error"),
        ("RelocOverflow", "重定位溢出（地址超出范围）", "使用大地址模型", "Error"),
        ("ArchMismatch", "目标架构与库架构不匹配", "使用匹配架构的库", "Error"),
        ("AbiMismatch", "链接对象 ABI 不兼容", "统一编译 ABI", "Error"),
        ("LinkScriptError", "链接脚本（linker script）错误", "修正链接脚本", "Error"),
        ("StaticDynamicConflict", "静态/动态链接方式冲突", "统一链接方式", "Error"),
        ("StdLibLinkFailed", "标准库链接失败", "检查标准库路径", "Error"),
        ("RuntimeLibMissing", "运行时库缺失", "配置运行时库", "Error"),
        ("LinkerOOM", "链接器内存耗尽", "减少链接单元或增量链接", "Error"),
        ("LinkerTimeout", "链接超时", "减少链接规模或增加超时", "Error"),
        ("ThreadLocalLink", "线程局部变量链接失败", "检查 TLS 模型", "Error"),
        ("WeakSymbolUnresolved", "弱符号未解析到实现", "提供弱符号定义", "Warning"),
        ("ExportSymbolMissing", "导出符号缺失：{symbol}", "显式导出符号", "Error"),
        ("ImportLibraryMissing", "导入库（import lib）缺失", "提供导入库", "Error"),
        ("COMDATConflict", "COMDAT 段冲突", "统一 comdat 选择", "Error"),
        ("LinkOrderError", "链接顺序错误导致符号未解析", "调整库顺序", "Error"),
        ("BitcodeLinkFailed", "bitcode 链接失败", "改用对象文件链接", "Error"),
        ("LTOFailed", "链接时优化（LTO）失败", "禁用 LTO", "Warning"),
        ("LinkerScriptUnknown", "链接脚本含未知命令", "修正脚本语法", "Error"),
        ("DynamicLibMissing", "动态库 {lib} 运行时缺失", "安装运行依赖", "Error"),
        ("RpathInvalid", "rpath 配置非法", "修正 rpath", "Error"),
        ("SymbolVisibility", "符号可见性导致未链接", "调整符号可见性", "Error"),
        ("LinkerLangMismatch", "链接对象语言（C/C++）不匹配", "统一语言前端", "Error"),
        ("GCSectionsFailed", "垃圾段回收（gc-sections）失败", "关闭 gc-sections", "Warning"),
        ("MmapLinkFailed", "链接器内存映射失败", "减小链接规模", "Error"),
        ("LinkSanitizer", "链接消毒剂运行时失败", "配置 sanitizer 运行时", "Error"),
        ("DeadStripFailed", "死符号剥离失败", "关闭死剥离", "Warning"),
        ("LinkerPluginError", "链接器插件错误", "移除或更新插件", "Error"),
        ("CrtFileMissing", "C 运行时启动文件缺失", "安装工具链 C 运行时", "Error"),
        ("LinkerVersionOld", "链接器版本过旧不支持特性", "升级链接器", "Error"),
        ("MangledNameConflict", "名称修饰（mangling）冲突", "统一修饰方案", "Error"),
        ("PieUnsupported", "目标不支持位置无关可执行（PIE）", "禁用 PIE", "Error"),
        ("LinkerStackSize", "链接指定的栈大小非法", "使用合法栈大小", "Error"),
        ("UnwindLibMissing", "展开库（unwind lib）缺失", "配置展开库", "Error"),
    ]),
    ("Abi", "E14", "后端", "ABI/FFI（二进制接口）", [
        ("FfiSignatureMismatch", "FFI 函数签名与 C 侧不匹配", "核对 C 侧声明", "Error"),
        ("FfiTypeUnsupported", "FFI 不支持该类型：{ty}", "改用兼容类型", "Error"),
        ("CAbiMismatch", "C ABI 调用约定不匹配", "统一调用约定", "Error"),
        ("StructLayoutMismatch", "结构体内存布局（padding/align）与 C 不一致", "使用 repr(C)", "Error"),
        ("EnumReprMismatch", "枚举内存表示与 C 不一致", "指定 repr 标注", "Error"),
        ("UnionLayout", "联合体布局与 C 不匹配", "使用 repr(C) 联合体", "Error"),
        ("CallbackAbiMismatch", "回调函数 ABI 不匹配", "标注正确的函数指针 ABI", "Error"),
        ("VarargsUnsupported", "不支持可变参数（varargs）FFI", "改用显式参数", "Error"),
        ("FfiUnsafeCall", "FFI 调用缺少 unsafe 标注", "添加 unsafe 块", "Error"),
        ("FfiLifetimeViolation", "FFI 返回引用生命周期无法保证", "使用拥有型返回值", "Error"),
        ("FfiPanicAcross", "跨 FFI 边界发生 panic（未定义行为）", "在边界捕获 panic", "Error"),
        ("FfiAllocMismatch", "FFI 两侧内存分配器不一致", "统一分配/释放侧", "Error"),
        ("FloatAbiMismatch", "浮点 ABI（hard/soft）不匹配", "统一浮点 ABI", "Error"),
        ("RegisterAbiMismatch", "寄存器级 ABI 约定不一致", "检查目标 ABI", "Error"),
        ("EndiannessMismatch", "字节序（endian）不匹配", "显式处理字节序", "Error"),
        ("AlignAbiMismatch", "对齐（alignment）要求不一致", "使用对齐标注", "Error"),
        ("NameMangling", "FFI 名称修饰（mangling）不匹配", "使用 extern 名称", "Error"),
        ("FfiCharEncoding", "字符编码在 FFI 边界不一致", "统一字符串编码", "Error"),
        ("FfiBoolSize", "布尔类型大小在 ABI 中不一致", "使用 C 兼容布尔", "Error"),
        ("FfiEnumSize", "枚举在 C 侧大小不确定", "指定枚举 repr", "Error"),
        ("FfiPointerNull", "FFI 接收到空指针但类型非可空", "检查 C 侧返回", "Error"),
        ("FfiWideChar", "宽字符（wchar）宽度不匹配", "使用固定宽度字符类型", "Error"),
        ("FfiLongSize", "long 类型宽度在平台上不一致", "使用定宽整数", "Error"),
        ("FfiStructPass", "结构体按值传递 ABI 不匹配", "改为指针传递", "Error"),
        ("FfiUnwindAbi", "FFI 边界展开（unwind）约定冲突", "统一展开策略", "Error"),
        ("FfiVectorAbi", "向量类型 ABI 不匹配", "使用标量或对齐向量", "Error"),
        ("FfiComplexType", "复数类型 ABI 不兼容", "使用结构体表示复数", "Error"),
        ("FfiBitfield", "位域（bitfield）布局跨语言不一致", "手动打包位域", "Error"),
        ("FfiVaList", "va_list 类型在 FFI 中不可用", "避免传递 va_list", "Error"),
        ("FfiThreadLocal", "线程局部在 FFI 边界不可见", "使用显式上下文传递", "Error"),
        ("FfiCallingConvention", "调用约定（cdecl/stdcall）不匹配", "标注正确调用约定", "Error"),
        ("FfiNonPod", "非 POD 类型跨越 FFI 边界", "仅传递 POD 类型", "Error"),
        ("FfiDtorLeak", "FFI 拥有对象析构责任不清导致泄漏", "明确所有权", "Error"),
        ("FfiCallbackLifetime", "FFI 回调生命周期短于注册方", "延长回调所有权", "Error"),
        ("FfiResourceLeak", "FFI 资源未释放", "在边界释放资源", "Error"),
        ("FfiSignalUnsafe", "在 FFI 中使用信号不安全操作", "改用安全替代", "Warning"),
        ("FfiLongjmp", "FFI 跨越 setjmp/longjmp 破坏栈", "避免跨边界跳转", "Error"),
        ("FfiComdat", "FFI 符号 comdat 选择冲突", "统一 comdat", "Error"),
        ("FfiTypeSize", "类型大小在两侧不一致", "检查类型定义", "Error"),
        ("FfiConstMismatch", "const 限定在 C 侧不一致", "统一 const 标注", "Warning"),
    ]),
    ("Concurrency", "E51", "运行期", "Concurrency（并发/协程）", [
        ("ThreadSpawnFailed", "线程创建失败：{reason}", "检查系统线程上限", "Error"),
        ("ThreadLimitExceeded", "线程数量超过上限：{limit}", "复用线程池", "Error"),
        ("DataRaceDetected", "检测到数据竞争（data race）", "使用同步原语保护共享数据", "Fatal"),
        ("DeadlockDetected", "检测到死锁", "调整加锁顺序", "Fatal"),
        ("LockPoisoned", "锁因持有者 panic 而中毒（poisoned）", "处理中毒锁", "Error"),
        ("CondVarSpurious", "条件变量伪唤醒（spurious wakeup）未处理", "在循环中检查条件", "Error"),
        ("ChannelClosed", "向已关闭的信道发送消息", "发送前检查信道状态", "Error"),
        ("ChannelSendBlocked", "信道发送永久阻塞（无接收方）", "使用带超时的发送", "Error"),
        ("ChannelRecvEmpty", "从空信道接收阻塞", "检查接收时机", "Error"),
        ("ActorMailboxFull", "actor 邮箱已满", "限流或增大邮箱", "Error"),
        ("ActorStopped", "向已停止的 actor 发送消息", "检查 actor 生命周期", "Error"),
        ("FutureNotPolled", "Future 未被轮询（未驱动执行）", "将 Future 交给执行器", "Error"),
        ("ExecutorShutdown", "向已关闭的执行器提交任务", "检查执行器生命周期", "Error"),
        ("AwaitOutsideAsync", "在非 async 上下文中使用 await", "将函数声明为 async", "Error"),
        ("AsyncRecursion", "async 递归导致栈溢出（未使用 Box）", "使用 BoxFuture 包装", "Error"),
        ("CoroutineSuspendInvalid", "协程在非挂起点被挂起", "仅在合法挂起点挂起", "Error"),
        ("CoroutineLeak", "协程泄漏（未结束且未被引用）", "确保协程完成或被取消", "Warning"),
        ("AtomicMisuse", "原子操作误用（非原子访问/内存序错误）", "统一使用原子操作", "Error"),
        ("MemoryOrderInvalid", "指定的内存序（memory order）非法", "使用合法内存序", "Error"),
        ("RwLockDeadlock", "读写锁死锁", "避免写者饥饿", "Error"),
        ("MutexDoubleLock", "同一线程重复加锁（不可重入）", "使用可重入锁", "Error"),
        ("BarrierWait", "屏障（barrier）等待数量不匹配", "统一参与者数量", "Error"),
        ("SemaphoreOverflow", "信号量（semaphore）释放超过初始值", "检查释放逻辑", "Error"),
        ("OnceInitPanic", "一次性初始化因 panic 永久失败", "修复初始化逻辑", "Error"),
        ("ThreadLocalAccess", "线程局部变量跨线程访问非法", "使用线程安全存储", "Error"),
        ("RaceOnInit", "静态初始化期间发生竞争", "使用安全惰性初始化", "Error"),
        ("ParkUnparkLost", "unpark 信号在 park 前丢失", "使用条件变量替代", "Error"),
        ("TaskCanceled", "任务被取消但资源未清理", "在取消路径释放资源", "Error"),
        ("AffinityFailed", "设置线程亲和性失败", "检查系统支持", "Error"),
        ("StackSizeInvalid", "协程/线程栈大小非法", "使用合法栈大小", "Error"),
        ("AsyncDropCycle", "async Drop 形成循环", "打破 Drop 循环", "Error"),
        ("ExecutorStarvation", "执行器线程饥饿", "调整任务调度", "Warning"),
        ("SelectArmConflict", "select! 多臂类型冲突", "统一臂类型", "Error"),
        ("ChannelCapacityZero", "容量为 0 的信道使用不当", "使用带缓冲或 rendezvous", "Error"),
        ("LockOrderInversion", "加锁顺序倒置导致潜在死锁", "统一全局加锁顺序", "Error"),
        ("NonSendCaptured", "跨线程捕获了非 Send 值", "仅捕获 Send 值", "Error"),
        ("NonSyncShared", "跨线程共享了非 Sync 值", "使用同步包装", "Error"),
        ("WatchdogTimeout", "看门狗（watchdog）超时杀进程", "检查任务耗时", "Fatal"),
        ("CpuAffinityUnsupported", "当前平台不支持 CPU 亲和性", "移除亲和性设置", "Warning"),
        ("CoroutineStackExhaust", "协程栈耗尽", "增大协程栈或减小帧", "Fatal"),
        ("WorkStealFailed", "工作窃取（work-stealing）失衡", "调整调度策略", "Warning"),
    ]),
    ("Mem", "E52", "运行期", "Memory（内存/GC）", [
        ("OutOfMemory", "内存分配失败（OOM）", "释放内存或增大配额", "Fatal"),
        ("DoubleFree", "检测到重复释放（double free）", "确保每个分配释放一次", "Fatal"),
        ("UseAfterFree", "释放后使用（use-after-free）", "避免使用已释放内存", "Fatal"),
        ("HeapCorruption", "堆内存损坏", "检查越界写入", "Fatal"),
        ("LeakDetected", "检测到内存泄漏（{bytes} 字节）", "释放未释放的对象", "Warning"),
        ("InvalidFree", "对非堆地址调用释放", "仅释放堆分配地址", "Fatal"),
        ("UnalignedAccess", "未对齐的内存访问", "使用对齐类型/地址", "Fatal"),
        ("NullDereference", "空指针解引用", "使用前判空", "Fatal"),
        ("BufferOverflow", "缓冲区溢出（写越界）", "检查边界", "Fatal"),
        ("BufferUnderflow", "缓冲区下溢（写越界）", "检查索引", "Fatal"),
        ("StackOverflow", "栈溢出", "减少递归深度", "Fatal"),
        ("GcPauseTooLong", "垃圾回收停顿过长（{ms} ms）", "调整 GC 策略", "Warning"),
        ("GcPromotionFailed", "GC 代际晋升失败", "检查对象可达性", "Error"),
        ("GcFragmentation", "GC 产生过多碎片", "使用压缩式 GC", "Warning"),
        ("GcCycleLeak", "GC 无法回收循环引用", "打破循环引用", "Warning"),
        ("FinalizerDeadlock", "终结器（finalizer）死锁", "避免终结器中加锁", "Error"),
        ("FinalizerRunsLate", "终结器延迟执行导致资源紧张", "显式释放资源", "Warning"),
        ("AllocatorMismatch", "分配器与释放器不匹配", "统一分配/释放侧", "Fatal"),
        ("CustomAllocFail", "自定义分配器返回空", "检查分配器实现", "Error"),
        ("AlignmentTooLarge", "请求的对齐超过分配器上限", "降低对齐要求", "Error"),
        ("ZeroSizeAlloc", "分配了零大小对象", "避免零大小分配", "Warning"),
        ("ReallocShrinkLost", "realloc 缩小导致数据丢失", "先复制再缩小", "Error"),
        ("MemoryMapFailed", "内存映射（mmap）失败", "检查映射大小与权限", "Error"),
        ("GuardPageViolation", "触发了保护页（guard page）", "检查栈/堆边界", "Fatal"),
        ("DanglingPointer", "悬垂指针访问", "避免使用已失效指针", "Fatal"),
        ("WildPointer", "野指针访问（未初始化指针）", "初始化指针后再使用", "Fatal"),
        ("ReferenceCycle", "引用计数循环导致泄漏", "改用弱引用打破循环", "Warning"),
        ("ArcStrongZero", "Arc 强引用计数异常归零", "检查并发计数", "Fatal"),
        ("WeakUpgradeFail", "弱引用升级（upgrade）失败", "处理升级失败分支", "Warning"),
        ("ArenaExhausted", "内存池（arena）耗尽", "增大池或复用", "Error"),
        ("ArenaDoubleFree", "内存池内重复释放", "确保每个槽位释放一次", "Fatal"),
        ("StackUnwindCorrupt", "栈展开时内存状态损坏", "检查异常安全", "Fatal"),
        ("MoveUninit", "移动了未初始化内存", "先初始化再移动", "Error"),
        ("ReadUninit", "读取了未初始化内存", "先初始化再读取", "Error"),
        ("PaddingLeak", "结构体内存填充（padding）含敏感数据", "显式清零填充", "Warning"),
        ("MemoryTagError", "内存标签（tag）校验失败（硬件内存安全）", "检查标签一致性", "Fatal"),
        ("HugepageFailed", "大页（hugepage）分配失败", "回退常规页", "Warning"),
        ("NumaBindFailed", "NUMA 绑定失败", "检查 NUMA 节点", "Error"),
        ("OvercommitExceeded", "内存过量提交超过限制", "减少内存使用", "Fatal"),
        ("GcRootLost", "GC 根集合丢失导致误回收", "保留根引用", "Fatal"),
        ("AllocatorDeadlock", "分配器内部死锁", "避免分配时持锁", "Fatal"),
    ]),
    ("Os", "E53", "运行期", "OS（系统调用）", [
        ("FileNotFound", "文件未找到：{path}", "检查文件路径", "Error"),
        ("PermissionDenied", "权限不足：{path}", "调整文件/目录权限", "Error"),
        ("IoError", "I/O 错误：{reason}", "重试或检查设备", "Error"),
        ("BrokenPipe", "管道（pipe）已断开", "处理写入断开", "Error"),
        ("TooManyOpenFiles", "打开文件数超过系统上限", "关闭不需要的文件描述符", "Error"),
        ("DiskFull", "磁盘空间不足", "清理磁盘或扩容", "Error"),
        ("NoSuchProcess", "目标进程不存在", "检查进程 ID", "Error"),
        ("ProcessSpawnFailed", "进程启动失败：{reason}", "检查命令与权限", "Error"),
        ("SignalReceived", "收到终止信号：{sig}", "处理信号或忽略", "Fatal"),
        ("TimeoutExceeded", "操作超时", "增大超时或优化耗时", "Error"),
        ("ResourceLimit", "超过系统资源限制", "调整系统限制", "Error"),
        ("AddressInUse", "网络地址已被占用：{addr}", "更换端口", "Error"),
        ("ConnectionRefused", "连接被拒绝", "检查服务状态", "Error"),
        ("NetworkUnreachable", "网络不可达", "检查网络配置", "Error"),
        ("DnsResolveFailed", "域名解析失败：{host}", "检查 DNS 配置", "Error"),
        ("EnvVarMissing", "环境变量 {var} 缺失", "设置环境变量", "Error"),
        ("EnvVarInvalid", "环境变量 {var} 取值非法", "修正环境变量", "Error"),
        ("WorkingDirMissing", "工作目录不存在", "切换有效目录", "Error"),
        ("SymlinkLoop", "符号链接形成循环", "断开链接循环", "Error"),
        ("ReadOnlyFileSystem", "文件系统只读", "使用可写文件系统", "Error"),
        ("QuotaExceeded", "磁盘配额超限", "清理或申请配额", "Error"),
        ("InvalidUtf8Path", "路径含非法 UTF-8", "使用合法路径编码", "Error"),
        ("ThreadPriorityFailed", "设置线程优先级失败", "检查系统权限", "Error"),
        ("ClockError", "系统时钟读取失败", "检查时钟源", "Error"),
        ("InsufficientMemory", "系统可用内存不足", "释放内存", "Error"),
        ("LockFileHeld", "文件锁被其他进程持有", "释放锁或重试", "Error"),
        ("SharedMemFailed", "共享内存创建失败", "检查共享内存配置", "Error"),
        ("MmapExecDenied", "内存映射执行权限被拒", "调整映射权限", "Error"),
        ("SeccompBlocked", "系统调用被 seccomp 拦截", "调整沙箱策略", "Error"),
        ("CapabilityMissing", "缺少系统能力（capability）", "授予所需能力", "Error"),
        ("ChrootFailed", "chroot 切换根目录失败", "检查目录与权限", "Error"),
        ("MountFailed", "挂载（mount）失败", "检查挂载点", "Error"),
        ("NoSuchDevice", "设备不存在：{dev}", "检查设备路径", "Error"),
        ("DeviceBusy", "设备忙", "稍后重试", "Error"),
        ("InvalidFd", "文件描述符无效", "检查描述符生命周期", "Error"),
        ("PollFailed", "I/O 多路复用（poll/epoll）失败", "检查事件源", "Error"),
        ("PipeBufferFull", "管道缓冲区已满", "消费端尽快读取", "Error"),
        ("ForkNotAllowed", "当前环境不支持 fork", "避免使用 fork", "Error"),
        ("ProcessAlreadyExited", "操作已退出进程", "检查进程状态", "Error"),
        ("UserNamespaceFailed", "用户命名空间创建失败", "检查命名空间支持", "Error"),
        ("FileSystemType", "不支持的文件系统类型", "使用受支持文件系统", "Error"),
    ]),
    ("Lsp", "E60", "全阶段", "LSP/IDE（编辑器协议）", [
        ("InvalidRequest", "LSP 请求非法：{method}", "检查客户端请求格式", "Error"),
        ("DocumentNotFound", "LSP 文档未找到：{uri}", "重新打开文档", "Error"),
        ("PositionOutOfRange", "LSP 位置超出文档范围", "检查行/列范围", "Error"),
        ("UnsupportedCapability", "客户端不支持该能力：{cap}", "升级客户端", "Warning"),
        ("DiagnosticsStale", "诊断结果过期（文档已变更）", "重新触发分析", "Warning"),
        ("SemanticTokensFailed", "语义高亮（semantic tokens）生成失败", "检查语法树", "Warning"),
        ("CompletionFailed", "补全（completion）生成失败", "检查上下文", "Warning"),
        ("HoverFailed", "悬停（hover）信息生成失败", "检查符号解析", "Warning"),
        ("DefinitionNotFound", "跳转定义目标未找到", "确认符号已定义", "Warning"),
        ("ReferenceSearchFailed", "引用查找失败", "检查索引", "Warning"),
        ("RenameFailed", "重命名（rename）失败：{name}", "检查跨文件引用", "Error"),
        ("FormatFailed", "格式化（formatting）失败", "检查语法合法性", "Error"),
        ("CodeActionFailed", "快速修复（code action）生成失败", "检查可用修复", "Warning"),
        ("InlayHintFailed", "内嵌提示（inlay hint）生成失败", "检查类型信息", "Warning"),
        ("FoldingFailed", "折叠（folding）范围计算失败", "检查语法结构", "Warning"),
        ("DocumentLinkFailed", "文档链接生成失败", "检查链接目标", "Warning"),
        ("WorkspaceSymbolFailed", "工作区符号检索失败", "检查索引完整性", "Warning"),
        ("ConfigurationMissing", "LSP 配置缺失：{key}", "补全客户端配置", "Warning"),
        ("ServerPanic", "语言服务器内部异常", "重启语言服务器", "Error"),
        ("ProtocolVersion", "LSP 协议版本不匹配", "对齐协议版本", "Error"),
        ("EncodingMismatch", "文档编码与服务器不一致", "统一 UTF-8 编码", "Error"),
        ("LineEndingMismatch", "行结束符不一致导致位置偏移", "统一行结束符", "Warning"),
        ("LargeDocument", "文档过大超过 LSP 处理上限", "拆分文档", "Warning"),
        ("DebounceSkipped", "防抖（debounce）期间跳过分析", "稍后重试", "Warning"),
        ("IndexCorrupt", "项目索引损坏", "重建索引", "Error"),
        ("SlowAnalysis", "分析耗时过长触发超时", "简化分析范围", "Warning"),
        ("MissingSource", "诊断引用的源码文件缺失", "确认文件路径", "Error"),
        ("UnknownDiagnostic", "收到未知诊断码：{code}", "升级诊断源", "Warning"),
        ("RpcParseFailed", "LSP JSON-RPC 解析失败", "检查传输层", "Error"),
        ("CancelledRequest", "请求被取消（客户端关闭）", "忽略即可", "Warning"),
        ("CrashRecovery", "语言服务器崩溃后恢复中", "等待恢复完成", "Warning"),
        ("WorkspaceFolder", "工作区文件夹未注册", "注册工作区", "Error"),
        ("FileWatcherFailed", "文件监视（watcher）失败", "检查文件系统事件", "Warning"),
        ("DiagnosticDuplicate", "重复诊断（已去重）", "检查诊断源", "Warning"),
        ("TelemetryDisabled", "遥测被禁用，无法上报", "启用遥测", "Warning"),
        ("ClientInitFailed", "客户端初始化握手失败", "检查初始化参数", "Error"),
        ("ProgressFailed", "进度（progress）通知失败", "检查进度令牌", "Warning"),
        ("LinkedEditingFailed", "联动编辑（linked editing）失败", "检查配对符号", "Warning"),
        ("CallHierarchyFailed", "调用层级（call hierarchy）失败", "检查调用图", "Warning"),
        ("TypeHierarchyFailed", "类型层级（type hierarchy）失败", "检查继承图", "Warning"),
        ("DocumentColorFailed", "文档颜色（color）提取失败", "检查颜色字面量", "Warning"),
    ]),
    ("Incremental", "E61", "全阶段", "Incremental（增量编译）", [
        ("CacheMissing", "增量编译缓存缺失，回退全量", "首次构建正常现象", "Warning"),
        ("CacheCorrupt", "增量缓存损坏", "清理增量缓存", "Error"),
        ("CacheVersionMismatch", "缓存版本与编译器不匹配", "清理并重建缓存", "Error"),
        ("DepFileStale", "依赖文件（.d）过期", "重新生成依赖", "Warning"),
        ("HashMismatch", "输入哈希不匹配，触发重编", "检查源文件变更", "Warning"),
        ("FingerprintFailed", "指纹（fingerprint）计算失败", "检查文件属性", "Error"),
        ("QueryCycle", "增量查询形成循环", "打破查询循环", "Error"),
        ("DirtyNode", "增量节点被标记为脏需重算", "重新分析该节点", "Warning"),
        ("SerializedFailed", "增量状态序列化失败", "检查缓存目录权限", "Error"),
        ("DeserializeFailed", "增量状态反序列化失败", "清理缓存重建", "Error"),
        ("CacheEvicted", "缓存条目被驱逐（容量限制）", "增大缓存或重编", "Warning"),
        ("UpToDateFalse", "误判为最新（实际需重编）", "强制重编一次", "Warning"),
        ("RebuildCascade", "一处变更引发大面积重编", "缩小变更范围", "Warning"),
        ("LockContention", "缓存锁竞争导致变慢", "减少并发写入", "Warning"),
        ("PermissionDenied", "缓存目录无写入权限", "修正缓存目录权限", "Error"),
        ("DiskFull", "缓存磁盘空间不足", "清理或扩容", "Error"),
        ("ConcurrentWrite", "并发写入缓存冲突", "串行化缓存写入", "Error"),
        ("MetadataMismatch", "模块元数据与缓存不一致", "清理缓存", "Error"),
        ("IncrementalDisabled", "配置禁用增量编译", "启用增量编译", "Warning"),
        ("ChangedEnv", "编译环境变更导致缓存失效", "稳定编译环境", "Warning"),
        ("ChangedFlags", "编译选项变更导致缓存失效", "保持编译选项稳定", "Warning"),
        ("ChangedTarget", "目标平台变更导致缓存失效", "清理跨目标缓存", "Warning"),
        ("FingerprintSalt", "指纹盐（salt）变更", "清理缓存", "Warning"),
        ("NodeLimit", "增量节点数超过上限", "拆分编译单元", "Warning"),
        ("GraphTooLarge", "依赖图过大导致内存压力", "模块化拆分", "Warning"),
        ("CachePathTooLong", "缓存路径过长（系统限制）", "缩短项目路径", "Error"),
        ("SymlinkCache", "符号链接导致缓存命中错误", "使用真实路径", "Warning"),
        ("ToolchainChanged", "工具链版本变化使缓存失效", "清理缓存", "Warning"),
        ("IncrementalPanic", "增量子系统异常", "清理缓存并重试", "Error"),
        ("QueryStackOverflow", "增量查询栈溢出", "减少递归查询", "Error"),
        ("CacheReadTimeout", "缓存读取超时", "检查存储性能", "Warning"),
        ("PersistentCache", "持久化缓存加载缓慢", "优化缓存存储", "Warning"),
        ("DirtyAll", "全量标记为脏（罕见）", "触发全量重编", "Warning"),
        ("HashCollision", "输入哈希冲突（极低概率）", "更换哈希策略", "Warning"),
        ("DepTrackingLost", "依赖追踪丢失", "重建依赖图", "Error"),
        ("IncrementalOOM", "增量状态内存耗尽", "减小缓存规模", "Error"),
        ("VersionDowngrade", "降级编译器导致缓存不可用", "清理旧缓存", "Warning"),
        ("CacheMigration", "缓存格式迁移失败", "清理并重建", "Error"),
        ("UntrackedInput", "存在未追踪的输入导致误命中", "登记全部输入", "Warning"),
    ]),
    ("Pkg", "E62", "全阶段", "Package（包管理）", [
        ("ManifestNotFound", "包清单（manifest）未找到", "创建或定位 manifest", "Error"),
        ("ManifestParse", "包清单解析失败：{reason}", "修正 manifest 语法", "Error"),
        ("DependencyMissing", "依赖 {dep} 未找到", "检查依赖名与源", "Error"),
        ("DependencyVersion", "依赖版本不满足：期望 {expected}", "调整版本约束", "Error"),
        ("DependencyConflict", "依赖版本冲突：{dep}", "统一版本约束", "Error"),
        ("RegistryUnreachable", "包仓库（registry）不可达", "检查网络/镜像", "Error"),
        ("DownloadFailed", "依赖下载失败：{dep}", "重试下载", "Error"),
        ("ChecksumMismatch", "依赖校验和（checksum）不匹配", "清理并重下", "Error"),
        ("LockfileStale", "锁定文件（lockfile）过期", "更新 lockfile", "Warning"),
        ("LockfileConflict", "lockfile 与 manifest 冲突", "重新解析依赖", "Error"),
        ("CircularDependency", "依赖存在循环", "打破依赖循环", "Error"),
        ("FeatureNotFound", "依赖特性（feature）不存在：{feat}", "检查特性名", "Error"),
        ("FeatureConflict", "依赖特性组合冲突", "调整特性启用", "Error"),
        ("BuildScriptFailed", "构建脚本（build script）失败", "检查构建脚本", "Error"),
        ("GitDependencyFailed", "Git 依赖克隆失败：{url}", "检查 Git 地址", "Error"),
        ("LocalPathMissing", "本地路径依赖不存在：{path}", "检查路径", "Error"),
        ("PublishDenied", "发布被拒绝：{reason}", "检查发布权限", "Error"),
        ("PackageNameInvalid", "包名非法：{name}", "使用合法包名", "Error"),
        ("PackageVersionInvalid", "包版本号非法", "使用语义化版本", "Error"),
        ("YankedPackage", "依赖版本已被撤回（yanked）", "升级到可用版本", "Warning"),
        ("UnresolvedProxy", "依赖代理（proxy）解析失败", "检查代理配置", "Error"),
        ("MirrorSync", "镜像同步延迟导致缺包", "切换镜像或等待", "Warning"),
        ("LicenseMissing", "缺少许可证声明", "补充许可证", "Warning"),
        ("LicenseConflict", "依赖许可证冲突", "检查许可证兼容", "Error"),
        ("PrivatePackage", "无权限访问私有包", "配置凭证", "Error"),
        ("TokenExpired", "仓库访问令牌过期", "刷新令牌", "Error"),
        ("PackageTooLarge", "包体积超过限制", "精简包内容", "Error"),
        ("InvalidMetadata", "包元数据非法", "修正元数据字段", "Error"),
        ("SourceIncompatible", "依赖源（source）类型不兼容", "统一依赖源", "Error"),
        ("PlatformSpecificDep", "依赖的平台条件不满足", "检查目标平台", "Error"),
        ("OptionalDepMissing", "可选依赖缺失但不影响构建", "忽略或安装可选依赖", "Warning"),
        ("DevDependencyLeak", "开发依赖被发布构建引用", "限定到 dev 依赖", "Error"),
        ("PatchConflict", "补丁（patch）依赖冲突", "调整补丁集", "Error"),
        ("WorkspaceMember", "工作区成员（member）未找到", "检查成员路径", "Error"),
        ("WorkspaceInherit", "工作区继承字段缺失", "在根配置补充", "Error"),
        ("OverridesConflict", "依赖覆盖（override）冲突", "统一覆盖规则", "Error"),
        ("VendoredMismatch", "vendor 目录与实际依赖不一致", "重新 vendor", "Error"),
        ("CachePermission", "包缓存目录无权限", "修正缓存权限", "Error"),
        ("ResolveTimeout", "依赖解析超时", "减少依赖图规模", "Error"),
        ("DuplicatePackage", "同一包被多次引入", "统一依赖来源", "Warning"),
        ("TargetSpecificManifest", "目标特定 manifest 解析失败", "检查目标字段", "Error"),
    ]),
    ("Build", "E63", "全阶段", "Build（构建系统）", [
        ("BuildScriptPanic", "构建脚本异常终止", "修复构建脚本", "Error"),
        ("BuildTargetMissing", "构建目标未定义：{target}", "检查构建配置", "Error"),
        ("BuildProfileUnknown", "构建配置（profile）未知：{profile}", "使用合法 profile", "Error"),
        ("ArtifactNotFound", "产物（artifact）未生成：{name}", "检查构建步骤", "Error"),
        ("CompileStepFailed", "编译步骤失败", "查看编译错误", "Error"),
        ("LinkStepFailed", "链接步骤失败", "查看链接错误", "Error"),
        ("CustomTargetFailed", "自定义目标（custom target）执行失败", "检查目标脚本", "Error"),
        ("BuildCacheInvalid", "构建缓存失效", "清理构建缓存", "Warning"),
        ("ParallelBuildDeadlock", "并行构建死锁", "减少并行度", "Error"),
        ("JobServerUnavailable", "作业服务器（jobserver）不可用", "禁用 jobserver", "Error"),
        ("OutputDirLocked", "输出目录被占用", "释放目录锁", "Error"),
        ("PermissionDenied", "无写入输出目录权限", "修正输出目录权限", "Error"),
        ("DiskFull", "构建磁盘空间不足", "清理或扩容", "Error"),
        ("BuildTimeout", "构建超时", "增大超时或减少规模", "Error"),
        ("IncrementalDisabled", "增量构建被禁用导致慢", "启用增量", "Warning"),
        ("FeatureGateBuild", "构建需特性开关未开启", "开启特性", "Error"),
        ("CrossCompileToolchain", "交叉编译工具链缺失", "安装目标工具链", "Error"),
        ("SysrootMissing", "系统根（sysroot）缺失", "配置 sysroot", "Error"),
        ("EnvVarMissing", "构建所需环境变量缺失：{var}", "设置环境变量", "Error"),
        ("BuildScriptEnv", "构建脚本读取了禁止的环境变量", "移除敏感环境依赖", "Error"),
        ("FingerprintMismatch", "构建指纹不匹配触发重编", "保持输入稳定", "Warning"),
        ("DepInfoStale", "依赖信息（depinfo）过期", "重新生成", "Warning"),
        ("TargetTripleInvalid", "目标三元组非法：{triple}", "检查三元组", "Error"),
        ("BuildPlanFailed", "构建计划（build plan）生成失败", "检查依赖图", "Error"),
        ("PostBuildFailed", "后处理（post-build）步骤失败", "检查后处理脚本", "Error"),
        ("TestHarnessFailed", "测试执行框架失败", "检查测试配置", "Error"),
        ("BenchHarnessFailed", "基准测试框架失败", "检查基准配置", "Error"),
        ("DocBuildFailed", "文档构建失败", "检查文档注释", "Error"),
        ("ExampleBuildFailed", "示例（example）构建失败", "检查示例代码", "Error"),
        ("ToolchainDownload", "工具链下载失败", "检查网络/镜像", "Error"),
        ("RustflagsConflict", "自定义编译标志冲突", "统一编译标志", "Error"),
        ("CfgNotDefined", "条件编译 cfg 未定义：{key}", "定义该 cfg", "Error"),
        ("BuildScriptRebuild", "构建脚本被重复触发重编", "稳定构建脚本输入", "Warning"),
        ("LockContention", "构建锁竞争", "减少并发写入", "Warning"),
        ("TargetSpecificFail", "仅在特定目标失败的构建", "检查目标条件", "Error"),
        ("OutOfMemory", "构建进程内存耗尽", "减少并行或拆分", "Error"),
        ("SignalInterrupted", "构建被信号中断", "重新构建", "Error"),
        ("TmpDirUnwritable", "临时目录不可写", "修正临时目录权限", "Error"),
        ("BuildHookFailed", "构建钩子（hook）执行失败", "检查钩子脚本", "Error"),
        ("UnsupportedAction", "构建动作不支持：{action}", "使用受支持动作", "Error"),
    ]),
    ("Debug", "E64", "全阶段", "Debugger（调试信息）", [
        ("DwarfEmitFailed", "DWARF 调试信息生成失败", "降低调试信息级别", "Error"),
        ("DebugInfoStripped", "调试信息被剥离（无法调试）", "保留调试信息", "Warning"),
        ("LineTableMissing", "行号表（line table）缺失", "启用行号生成", "Warning"),
        ("VariableLocation", "变量位置（location）信息丢失", "保留变量调试信息", "Warning"),
        ("TypeInfoMissing", "类型信息缺失（无法展开类型）", "包含完整类型信息", "Warning"),
        ("InlinedFrame", "内联帧（inlined frame）调试错位", "检查内联调试信息", "Warning"),
        ("BreakpointUnavailable", "无法在优化后设置断点", "降低优化级别", "Warning"),
        ("WatchpointFailed", "监视点（watchpoint）设置失败", "检查硬件支持", "Error"),
        ("SymbolNotFound", "调试符号未找到：{symbol}", "保留符号表", "Error"),
        ("SourceMapMissing", "源码映射（source map）缺失", "生成 source map", "Warning"),
        ("PdbEmitFailed", "PDB 调试数据库生成失败", "检查 PDB 路径", "Error"),
        ("DebuggerAttachFailed", "调试器附加（attach）失败", "检查权限/进程", "Error"),
        ("CoreDumpFailed", "核心转储（core dump）生成失败", "检查核心大小限制", "Error"),
        ("BacktraceUnavailable", "调用栈回溯不可用", "保留帧指针", "Warning"),
        ("OptimizedOut", "变量被优化掉无法查看", "使用 volatile 或降优化", "Warning"),
        ("DebugMacroInfo", "宏调试信息缺失", "启用宏调试信息", "Warning"),
        ("NamespaceInfoMissing", "命名空间调试信息缺失", "包含命名空间信息", "Warning"),
        ("TemplateInfoMissing", "模板/泛型调试信息缺失", "包含实例化信息", "Warning"),
        ("SplitDebugFailed", "分离调试信息（split debug）失败", "检查调试目录", "Error"),
        ("DebugCompression", "调试信息压缩失败", "关闭压缩", "Warning"),
        ("LineZero", "调试出现第 0 行（位置异常）", "检查源码位置传递", "Warning"),
        ("ColumnInfoMissing", "列号调试信息缺失", "启用列信息", "Warning"),
        ("InheritanceInfo", "继承关系调试信息缺失", "包含类型层级", "Warning"),
        ("AsyncBacktrace", "异步调用栈回溯断裂", "启用异步回溯", "Warning"),
        ("DebugPrettyPrinter", "pretty printer 注册失败", "检查调试脚本", "Warning"),
        ("EvalFailed", "调试器表达式求值失败", "检查表达式上下文", "Error"),
        ("ConditionalBreakpoint", "条件断点求值失败", "简化断点条件", "Warning"),
        ("DebugServerDown", "调试服务器（debug server）未运行", "启动调试服务器", "Error"),
        ("ProtocolHandshake", "调试协议握手失败", "检查调试器版本", "Error"),
        ("SymbolicateFailed", "符号化（symbolicate）失败", "提供符号文件", "Warning"),
        ("DebugInfoMismatch", "调试信息与二进制不匹配", "重新生成调试信息", "Error"),
        ("FrameCorrupt", "调用帧损坏无法展开", "检查栈完整性", "Error"),
        ("UnwindInfoMissing", "展开信息缺失导致回溯失败", "保留展开信息", "Warning"),
        ("DebugSectionsStripped", "调试段（.debug_*）被剥离", "保留调试段", "Warning"),
        ("TypeAliasInfo", "类型别名调试信息丢失", "包含别名解析", "Warning"),
        ("LocalVarOmitted", "局部变量调试条目被省略", "禁用变量省略", "Warning"),
        ("DebugInfoTooLarge", "调试信息过大", "降低调试级别", "Warning"),
        ("CorruptDebugInfo", "调试信息损坏", "重新生成", "Error"),
        ("MissingCompilationUnit", "编译单元（CU）调试信息缺失", "包含 CU 信息", "Warning"),
        ("DebugArangesMissing", "地址区间（aranges）表缺失", "生成 aranges", "Warning"),
    ]),
    ("Dist", "E65", "全阶段", "Distributed（分布式编译）", [
        ("RemoteNodeDown", "远程编译节点不可用", "检查节点状态", "Error"),
        ("SchedulerUnreachable", "编译调度器（scheduler）不可达", "检查网络", "Error"),
        ("JobDispatchFailed", "编译任务分发失败", "重试分发", "Error"),
        ("ResultFetchFailed", "远程结果拉取失败", "检查网络/存储", "Error"),
        ("NodeAuthFailed", "远程节点鉴权失败", "检查凭证", "Error"),
        ("InconsistentEnv", "远程与本地环境不一致", "统一工具链/依赖", "Error"),
        ("CacheSyncFailed", "分布式缓存同步失败", "检查缓存后端", "Error"),
        ("NetworkPartition", "网络分区导致编译中断", "恢复网络后重试", "Error"),
        ("TimeoutExceeded", "远程编译超时", "增大超时或拆分任务", "Error"),
        ("ResultCorrupt", "远程返回结果损坏", "重新分发任务", "Error"),
        ("NodeOverloaded", "远程节点过载", "分散到其他节点", "Warning"),
        ("ArtifactMismatch", "远程产物与本地期望不一致", "校验产物哈希", "Error"),
        ("UnsupportedTarget", "远程节点不支持该目标", "选择支持的目标节点", "Error"),
        ("CompilationUnitTooBig", "编译单元过大无法分发", "拆分编译单元", "Warning"),
        ("DependencyNotCached", "依赖未缓存到远程", "预上传依赖", "Warning"),
        ("SecureChannelFailed", "安全通道（TLS）建立失败", "检查证书", "Error"),
        ("HeartbeatLost", "节点心跳丢失", "检查节点健康", "Error"),
        ("QuotaExceeded", "编译配额超限", "申请更多配额", "Error"),
        ("RegionMismatch", "节点区域与数据合规冲突", "选择合规区域", "Error"),
        ("SerializationFailed", "任务序列化失败", "检查任务结构", "Error"),
        ("DeserializationFailed", "任务反序列化失败", "统一定义格式", "Error"),
        ("VersionSkew", "节点工具链版本不一致", "统一版本", "Error"),
        ("PartialFailure", "部分节点失败导致整体回退", "隔离失败节点", "Warning"),
        ("LoadImbalance", "负载不均衡", "优化调度策略", "Warning"),
        ("IdempotencyViolation", "重复分发导致非幂等结果", "去重任务", "Error"),
        ("CachePoisoned", "分布式缓存被污染", "清理缓存", "Error"),
        ("BandwidthLimited", "带宽受限拖慢编译", "就近调度节点", "Warning"),
        ("NodeBlacklisted", "节点被列入黑名单", "检查节点健康", "Warning"),
        ("CompilationAborted", "分布式编译被中止", "查看中止原因", "Error"),
        ("CheckpointFailed", "任务检查点（checkpoint）失败", "检查存储", "Error"),
        ("RecoverFailed", "故障恢复失败", "手动重试", "Error"),
        ("TokenExpired", "临时访问令牌过期", "刷新令牌", "Error"),
        ("MisconfiguredPool", "节点池配置错误", "修正池配置", "Error"),
        ("CompilationDrift", "多次编译结果漂移（不确定）", "固定环境变量", "Error"),
        ("AuditLogMissing", "审计日志缺失", "启用审计", "Warning"),
        ("ColdStart", "节点冷启动慢", "预热节点", "Warning"),
        ("ResourceContention", "多任务资源争用", "限流", "Warning"),
        ("UnsupportedFeature", "分布式不支持该编译特性", "本地编译该特性", "Error"),
    ]),
    ("Plugin", "E66", "全阶段", "Plugin（插件扩展）", [
        ("PluginNotFound", "插件未找到：{name}", "检查插件路径", "Error"),
        ("PluginLoadFailed", "插件加载失败：{reason}", "检查插件兼容", "Error"),
        ("PluginVersionMismatch", "插件版本与宿主不兼容", "升级插件或宿主", "Error"),
        ("PluginApiChanged", "插件使用的 API 已变更", "更新插件", "Error"),
        ("PluginPanic", "插件执行异常", "修复插件实现", "Error"),
        ("PluginTimeout", "插件执行超时", "优化插件或增大超时", "Error"),
        ("PluginPermissionDenied", "插件权限不足", "授予所需权限", "Error"),
        ("PluginConflict", "插件间功能冲突：{name}", "禁用冲突插件", "Error"),
        ("PluginSignatureInvalid", "插件签名校验失败", "使用受信任插件", "Error"),
        ("PluginUnsafeOperation", "插件执行了不安全操作", "审查插件来源", "Error"),
        ("PluginInitFailed", "插件初始化失败", "检查插件配置", "Error"),
        ("PluginDepMissing", "插件依赖缺失：{dep}", "安装插件依赖", "Error"),
        ("PluginConfigInvalid", "插件配置非法", "修正插件配置", "Error"),
        ("PluginHookError", "插件钩子（hook）执行失败", "检查钩子实现", "Error"),
        ("PluginResourceLeak", "插件泄漏资源", "修复插件资源释放", "Error"),
        ("PluginCrashed", "插件崩溃导致宿主降级", "更新插件", "Error"),
        ("PluginDisabled", "插件被禁用但被引用", "启用插件", "Warning"),
        ("PluginTooOld", "插件过旧不再受支持", "升级插件", "Warning"),
        ("PluginTooNew", "插件过新宿主不支持", "升级宿主", "Warning"),
        ("PluginNameConflict", "插件名冲突：{name}", "重命名插件", "Error"),
        ("PluginCycle", "插件依赖形成循环", "打破插件循环", "Error"),
        ("PluginSandboxViolation", "插件违反沙箱约束", "放宽沙箱或修正插件", "Error"),
        ("PluginOutOfMemory", "插件内存耗尽", "限制插件内存", "Error"),
        ("PluginDeadlock", "插件内部死锁", "审查插件并发", "Error"),
        ("PluginNetworkBlocked", "插件网络访问被拦", "配置网络策略", "Error"),
        ("PluginFileSystemBlocked", "插件文件系统访问被拦", "配置文件系统策略", "Error"),
        ("PluginEnvBlocked", "插件环境变量访问被拦", "配置环境策略", "Error"),
        ("PluginUnserialize", "插件状态反序列化失败", "清理插件状态", "Error"),
        ("PluginHotReloadFailed", "插件热重载失败", "重启加载插件", "Warning"),
        ("PluginUnloadFailed", "插件卸载失败", "强制释放插件", "Error"),
        ("PluginCapabilityMissing", "插件所需能力缺失：{cap}", "启用对应能力", "Error"),
        ("PluginDeprecated", "插件 API 已废弃", "迁移到新 API", "Warning"),
        ("PluginManifestInvalid", "插件清单非法", "修正插件清单", "Error"),
        ("PluginEntryMissing", "插件入口符号缺失", "检查插件导出", "Error"),
        ("PluginAbiMismatch", "插件 ABI 与宿主不匹配", "重新编译插件", "Error"),
        ("PluginLangMismatch", "插件语言运行时不匹配", "使用兼容运行时", "Error"),
        ("PluginBadExit", "插件以错误码退出", "查看插件日志", "Error"),
        ("PluginStdoutParse", "插件输出解析失败", "规范插件输出", "Warning"),
        ("PluginLockContention", "插件锁竞争", "减少插件并发", "Warning"),
    ]),
    ("Tgt", "E67", "后端", "Target（目标平台）", [
        ("TargetTripleInvalid", "目标三元组（triple）无效：{triple}", "检查目标拼写", "Error"),
        ("TargetUnsupported", "目标平台不受支持：{target}", "选择受支持目标", "Error"),
        ("TargetFeatureMissing", "目标缺少特性 {feature}", "启用目标特性", "Error"),
        ("TargetArchUnknown", "未知目标架构：{arch}", "使用已知架构", "Error"),
        ("TargetOsUnknown", "未知目标操作系统：{os}", "使用已知 OS", "Error"),
        ("TargetEnvUnknown", "未知目标环境（env）：{env}", "使用已知 env", "Error"),
        ("TargetVendorUnknown", "未知目标厂商（vendor）：{vendor}", "使用已知 vendor", "Error"),
        ("TargetPointerWidth", "目标指针宽度不支持：{width}", "选择受支持宽度", "Error"),
        ("TargetEndianUnknown", "目标字节序未知", "显式指定字节序", "Error"),
        ("TargetFloatUnsupported", "目标不支持硬件浮点", "使用软浮点", "Error"),
        ("TargetAtomicMissing", "目标不支持原子指令", "使用锁替代", "Error"),
        ("TargetSimdAbsent", "目标无 SIMD 指令集", "禁用向量化", "Error"),
        ("TargetTlsModel", "目标 TLS 模型不支持", "更换 TLS 模型", "Error"),
        ("TargetRelocation", "目标不支持该重定位", "调整代码生成", "Error"),
        ("TargetCodeModel", "目标代码模型（code model）非法", "使用合法代码模型", "Error"),
        ("TargetCpuUnknown", "未知目标 CPU：{cpu}", "使用已知 CPU", "Error"),
        ("TargetFpuUnknown", "未知目标 FPU：{fpu}", "使用已知 FPU", "Error"),
        ("TargetAbiUnknown", "未知目标 ABI：{abi}", "使用已知 ABI", "Error"),
        ("TargetPanicStrategy", "目标不支持该 panic 策略", "使用受支持策略", "Error"),
        ("TargetAllocStrategy", "目标分配策略不支持", "更换分配器", "Error"),
        ("TargetSyscallConv", "目标系统调用约定未知", "使用目标约定", "Error"),
        ("TargetStackProbe", "目标栈探测（stack probe）不支持", "禁用栈探测", "Error"),
        ("TargetExceptionModel", "目标异常模型不支持", "使用受支持模型", "Error"),
        ("TargetDebugFormat", "目标调试格式不支持", "更换调试格式", "Error"),
        ("TargetObjFormat", "目标目标文件格式不支持", "使用受支持格式", "Error"),
        ("TargetLinkerMissing", "目标链接器缺失", "安装目标链接器", "Error"),
        ("TargetRuntimeMissing", "目标运行时库缺失", "配置目标运行时", "Error"),
        ("TargetLibcMissing", "目标 libc 缺失", "提供目标 libc", "Error"),
        ("TargetNoStd", "目标无标准库支持", "使用 no_std 模式", "Error"),
        ("TargetNoAtomic", "目标无原子支持且禁用 fallback", "启用原子 fallback", "Error"),
        ("TargetUnsupportedFloat", "目标浮点类型不支持", "改用整型表示", "Error"),
        ("TargetRegisterWidth", "目标寄存器宽度不支持", "调整数据类型", "Error"),
        ("TargetProfiling", "目标不支持性能分析插桩", "关闭插桩", "Warning"),
        ("TargetSanitizerAbsent", "目标不支持消毒剂", "关闭 sanitizer", "Warning"),
        ("TargetCoverage", "目标不支持覆盖率插桩", "关闭覆盖率", "Warning"),
        ("TargetPositionIndependent", "目标不支持位置无关代码", "禁用 PIC", "Error"),
        ("TargetThreadLocal", "目标不支持线程局部", "避免使用 TLS", "Error"),
        ("TargetUnwindUnsupported", "目标不支持栈展开", "使用不展开 panic 策略", "Error"),
        ("TargetVendorLibMissing", "目标厂商库缺失", "安装厂商 SDK", "Error"),
    ]),
    ("Simd", "E68", "后端", "SIMD（向量化）", [
        ("SimdWidthUnsupported", "SIMD 宽度 {width} 不支持", "使用受支持宽度", "Error"),
        ("SimdTypeMismatch", "SIMD 向量类型不匹配", "统一向量长度/类型", "Error"),
        ("SimdLaneCount", "SIMD 通道数（lane）非法：{lanes}", "使用合法通道数", "Error"),
        ("SimdUnaligned", "SIMD 未对齐访问", "使用对齐加载/存储", "Error"),
        ("SimdMaskInvalid", "SIMD 掩码（mask）非法", "检查掩码位宽", "Error"),
        ("SimdReductionFailed", "SIMD 归约（reduction）失败", "改用标量归约", "Error"),
        ("SimdShuffleInvalid", "SIMD 重排（shuffle）索引越界", "检查索引范围", "Error"),
        ("SimdGatherScatter", "SIMD 聚集/散布（gather/scatter）不支持", "使用标量回退", "Error"),
        ("SimdIntrinsicMissing", "SIMD 内建指令缺失：{name}", "使用受支持指令", "Error"),
        ("SimdOverflow", "SIMD 运算溢出", "检查数据范围", "Error"),
        ("SimdDivByZero", "SIMD 除零", "检查分母通道", "Error"),
        ("SimdNanPropagate", "SIMD 产生非数（NaN）未处理", "检查输入有效性", "Warning"),
        ("SimdConstantInvalid", "SIMD 常量构造非法", "检查常量类型", "Error"),
        ("SimdCvtFailed", "SIMD 类型转换（convert）失败", "使用兼容类型", "Error"),
        ("SimdPermuteFailed", "SIMD 置换（permute）失败", "检查置换模式", "Error"),
        ("SimdBlendInvalid", "SIMD 混合（blend）掩码非法", "检查掩码", "Error"),
        ("SimdExtractOob", "SIMD 提取（extract）越界", "检查通道索引", "Error"),
        ("SimdInsertOob", "SIMD 插入（insert）越界", "检查通道索引", "Error"),
        ("SimdCompareResult", "SIMD 比较结果类型不匹配", "使用掩码类型", "Error"),
        ("SimdBitcast", "SIMD 位转换（bitcast）非法", "检查位宽", "Error"),
        ("SimdAlignment", "SIMD 对齐要求不满足", "使用对齐分配", "Error"),
        ("SimdTargetAbsent", "目标无对应 SIMD ISA", "禁用该 SIMD 路径", "Error"),
        ("SimdLengthMismatch", "SIMD 操作数长度不一致", "统一向量长度", "Error"),
        ("SimdSignedUnsigned", "SIMD 有/无符号混用错误", "统一符号", "Error"),
        ("SimdRounding", "SIMD 舍入模式不支持", "使用默认舍入", "Warning"),
        ("SimdSaturation", "SIMD 饱和（saturation）不支持", "使用标量回退", "Warning"),
        ("SimdFmaMissing", "SIMD 融合乘加（FMA）不支持", "拆分乘加", "Warning"),
        ("SimdConflict", "多 SIMD 指令集冲突", "固定使用一种 ISA", "Error"),
        ("SimdRegisterPressure", "SIMD 寄存器压力过高", "减少同时活动向量", "Warning"),
        ("SimdLaneOrder", "SIMD 通道顺序（endian）不一致", "统一通道序", "Error"),
        ("SimdPredicateInvalid", "SIMD 谓词（predicate）非法", "检查谓词", "Error"),
        ("SimdRotated", "SIMD 旋转（rotate）不支持", "改用移位组合", "Warning"),
        ("SimdPopcount", "SIMD 位计数（popcount）不支持", "使用标量回退", "Warning"),
        ("SimdShiftOob", "SIMD 移位量越界", "检查移位量", "Error"),
        ("SimdSelectInvalid", "SIMD 选择（select）掩码非法", "检查掩码", "Error"),
        ("SimdWidenFailed", "SIMD 加宽（widen）失败", "使用显式加宽", "Error"),
        ("SimdNarrowFailed", "SIMD 收窄（narrow）溢出", "检查数据范围", "Error"),
        ("SimdInterleave", "SIMD 交织（interleave）失败", "检查输入布局", "Error"),
        ("SimdDeinterleave", "SIMD 去交织（deinterleave）失败", "检查输入布局", "Error"),
    ]),
    ("Embed", "E69", "后端", "Embedded（嵌入式/CGO）", [
        ("EmbedNoStd", "嵌入式目标无标准库", "使用 no_std 模式", "Error"),
        ("EmbedNoAlloc", "嵌入式目标无分配器", "使用静态分配", "Error"),
        ("EmbedFlashFull", "嵌入式 Flash 空间不足", "精简固件", "Error"),
        ("EmbedRamFull", "嵌入式 RAM 不足", "减少静态占用", "Error"),
        ("EmbedNoFloat", "嵌入式目标无 FPU", "使用定点数", "Error"),
        ("EmbedNoException", "嵌入式目标禁用异常", "使用错误码返回", "Error"),
        ("EmbedNoRtti", "嵌入式目标禁用 RTTI", "避免运行时类型查询", "Error"),
        ("EmbedHardFault", "触发硬件错误（HardFault）", "检查外设/内存访问", "Fatal"),
        ("EmbedWatchdog", "看门狗（watchdog）复位", "喂狗或优化耗时", "Fatal"),
        ("EmbedInterruptNested", "中断嵌套过深", "减少中断嵌套", "Error"),
        ("EmbedStackOverflow", "嵌入式栈溢出", "增大栈或减帧", "Fatal"),
        ("EmbedHeapCorrupt", "嵌入式堆损坏", "检查越界写入", "Fatal"),
        ("EmbedPeripheralBusy", "外设忙（忙等待超时）", "检查外设状态", "Error"),
        ("EmbedDmaFailed", "DMA 传输失败", "检查 DMA 配置", "Error"),
        ("EmbedClockMisconfig", "时钟配置错误", "检查时钟树", "Error"),
        ("EmbedPinConflict", "引脚（pin）功能冲突", "重新分配引脚", "Error"),
        ("EmbedNoSyscall", "嵌入式目标无系统调用", "使用裸机 API", "Error"),
        ("CgoSymbolClash", "CGO 符号与 C 侧冲突", "使用命名空间前缀", "Error"),
        ("CgoTypeMismatch", "CGO 类型映射错误", "检查 cgo 类型标注", "Error"),
        ("CgoCallbackNull", "CGO 回调指针为空", "检查 C 侧注册", "Error"),
        ("CgoPanicCross", "CGO 跨边界 panic", "边界捕获 panic", "Fatal"),
        ("CgoThreadLocal", "CGO 线程局部不可见", "显式传递上下文", "Error"),
        ("CgoAllocMismatch", "CGO 跨语言释放内存", "统一分配侧", "Fatal"),
        ("EmbedInterruptPriority", "中断优先级配置非法", "检查 NVIC 配置", "Error"),
        ("EmbedBootFailed", "启动（boot）失败", "检查启动文件", "Fatal"),
        ("EmbedLinkerScript", "嵌入式链接脚本错误", "修正链接脚本", "Error"),
        ("EmbedVectorTable", "中断向量表缺失/错位", "检查向量表", "Fatal"),
        ("EmbedNoAtomic", "嵌入式目标无原子指令", "关闭并发或禁用", "Error"),
        ("EmbedWatchpoint", "嵌入式监视点不可用", "改用软件检测", "Warning"),
        ("EmbedPowerFail", "电源故障导致复位", "检查电源管理", "Fatal"),
        ("EmbedStackCanary", "栈金丝雀（canary）被破坏", "检查栈溢出", "Fatal"),
        ("EmbedMpuViolation", "MPU 保护区域违规", "调整 MPU 配置", "Fatal"),
        ("EmbedCacheCoherency", "缓存一致性（cache coherency）问题", "手动刷新缓存", "Warning"),
        ("CgoCcNotFound", "CGO 所需 C 编译器未找到", "安装 C 工具链", "Error"),
        ("CgoBuildFailed", "CGO 生成的 C 代码编译失败", "检查 C 代码", "Error"),
        ("EmbedNoStdio", "嵌入式目标无标准 IO", "使用自定义日志", "Warning"),
        ("EmbedTickFailed", "系统节拍（tick）初始化失败", "检查定时器", "Error"),
        ("EmbedCriticalSection", "临界区（critical section）嵌套错误", "平衡进入/退出", "Error"),
        ("EmbedNoFpu", "目标硬件无 FPU 触发软浮点异常", "启用软浮点", "Error"),
        ("CgoCallbackLifetime", "CGO 回调生命周期短于 C 侧", "延长回调所有权", "Fatal"),
    ]),
    ("Test", "E70", "全阶段", "Test（测试框架）", [
        ("TestCompileFailed", "测试代码编译失败", "修复测试代码", "Error"),
        ("TestBinaryMissing", "测试可执行文件未生成", "检查测试构建", "Error"),
        ("TestTimeout", "测试用例超时", "优化用例或增大超时", "Error"),
        ("TestPanic", "测试中出现 panic", "修复被测逻辑", "Error"),
        ("TestAssertFailed", "断言失败：{msg}", "检查预期与实际", "Error"),
        ("TestFixtureFailed", "测试夹具（fixture）初始化失败", "检查夹具逻辑", "Error"),
        ("TestTeardownFailed", "测试清理（teardown）失败", "检查清理逻辑", "Error"),
        ("TestFilterNoMatch", "测试过滤器未匹配任何用例", "检查过滤表达式", "Warning"),
        ("TestDuplicateName", "测试用例名重复：{name}", "重命名用例", "Error"),
        ("TestDependencyOrder", "测试依赖顺序错误", "显式声明依赖", "Error"),
        ("TestResourceLeak", "测试泄漏资源", "在 teardown 释放", "Warning"),
        ("TestIgnored", "测试用例被忽略（ignore）", "检查忽略条件", "Warning"),
        ("TestShouldPanic", "期望 panic 但未发生", "修正预期", "Error"),
        ("TestUnexpectedPanic", "未期望的 panic 发生", "修复被测代码", "Error"),
        ("TestFlaky", "测试不稳定（flaky）", "消除时序依赖", "Warning"),
        ("TestHarnessCrash", "测试框架崩溃", "升级测试框架", "Error"),
        ("TestStdoutCapture", "测试输出捕获失败", "检查输出重定向", "Warning"),
        ("TestEnvMissing", "测试所需环境变量缺失", "设置环境变量", "Error"),
        ("TestDataMissing", "测试数据文件缺失：{path}", "补充测试数据", "Error"),
        ("TestMockFailed", "Mock 对象行为不匹配", "修正 mock 设定", "Error"),
        ("TestConcurrency", "并发测试竞态", "使用同步原语", "Error"),
        ("TestDeadlock", "测试内部死锁", "检查加锁顺序", "Error"),
        ("TestLeakSanitizer", "测试触发泄漏检测", "释放测试资源", "Error"),
        ("TestCoverageFailed", "覆盖率采集失败", "检查插桩", "Warning"),
        ("TestReportFailed", "测试报告生成失败", "检查报告路径", "Error"),
        ("TestParallelConflict", "并行测试共享状态冲突", "隔离测试状态", "Error"),
        ("TestBeforeAllFailed", "全局前置（before-all）失败", "检查前置逻辑", "Error"),
        ("TestAfterAllFailed", "全局后置（after-all）失败", "检查后置逻辑", "Error"),
        ("TestSkipCondition", "测试跳过条件误触发", "检查跳过逻辑", "Warning"),
        ("TestParamMismatch", "参数化测试参数不匹配", "检查参数集", "Error"),
        ("TestTimeoutConfig", "测试超时配置非法", "使用合法超时", "Error"),
        ("TestBinaryCrash", "测试进程崩溃", "检查被测代码", "Fatal"),
        ("TestSignal", "测试收到意外信号", "检查信号处理", "Error"),
        ("TestMemoryLimit", "测试超过内存限制", "减少内存使用", "Error"),
        ("TestIsolation", "测试间未隔离导致相互影响", "隔离测试环境", "Error"),
        ("TestRandomSeed", "随机测试种子未固定导致不稳定", "固定随机种子", "Warning"),
        ("TestImportFailed", "测试辅助模块导入失败", "检查测试路径", "Error"),
        ("TestUnknownAttr", "未知测试属性（attr）", "移除无效属性", "Warning"),
        ("TestDoubleRun", "同一用例被执行两次", "检查测试发现逻辑", "Warning"),
        ("TestSummaryLost", "测试汇总信息丢失", "检查输出通道", "Error"),
        ("TestHang", "测试挂起（hang）", "检查阻塞调用", "Error"),
    ]),
    ("Doc", "E71", "全阶段", "Doc（文档/Doctest）", [
        ("DocBrokenLink", "文档存在断链：{url}", "修正链接地址", "Warning"),
        ("DocMissingItem", "文档引用的条目不存在：{name}", "补充条目或修正引用", "Warning"),
        ("DocCodeBlockFailed", "文档代码块（rust/cangjie）执行失败", "修正示例代码", "Error"),
        ("DocTestFailed", "文档测试（doctest）失败", "修正文档示例", "Error"),
        ("DocExamplePanic", "文档示例 panic", "修正示例逻辑", "Error"),
        ("DocCompileFailed", "文档示例编译失败", "修复示例代码", "Error"),
        ("DocMalformedAttr", "文档属性非法", "修正文档属性", "Warning"),
        ("DocCyclicModule", "文档模块引用循环", "打破文档循环", "Warning"),
        ("DocPrivateLeak", "文档泄露了私有项", "调整可见性或 #[doc(hidden)]", "Warning"),
        ("DocHtmlEscape", "文档 HTML 转义失败", "检查特殊字符", "Warning"),
        ("DocMissingSummary", "文档缺少摘要（summary）", "补充条目首句", "Warning"),
        ("DocBrokenIntraLink", "文档内部链接（intra-doc）失效", "修正内部路径", "Warning"),
        ("DocAliasConflict", "文档别名冲突", "统一文档别名", "Warning"),
        ("DocSearchIndex", "文档搜索索引生成失败", "检查文档结构", "Warning"),
        ("DocThemeFailed", "文档主题渲染失败", "使用默认主题", "Warning"),
        ("DocAssetMissing", "文档资源（图片/JS）缺失", "补充资源文件", "Warning"),
        ("DocCommentTooLong", "文档注释过长", "精简文档", "Warning"),
        ("DocNonAsciiPath", "文档路径含非 ASCII 字符", "使用 ASCII 路径", "Warning"),
        ("DocVersionMismatch", "文档版本与代码不一致", "同步文档版本", "Warning"),
        ("DocExampleOutdated", "文档示例已过时", "更新示例", "Warning"),
        ("DocInvalidMarkdown", "文档 Markdown 语法非法", "修正 Markdown", "Warning"),
        ("DocTableBroken", "文档表格格式错误", "修正表格", "Warning"),
        ("DocCodeLangUnknown", "文档代码块语言未知", "指定已知语言", "Warning"),
        ("DocRedirectLoop", "文档重定向循环", "修正重定向", "Warning"),
        ("DocCrossCrate", "跨 crate 文档链接失效", "检查外部文档", "Warning"),
        ("DocFeatureGate", "文档特性未开启导致缺失", "开启文档特性", "Warning"),
        ("DocJsonFailed", "文档 JSON 输出生成失败", "检查文档结构", "Error"),
        ("DocTestCompileTimeout", "文档测试编译超时", "简化示例", "Warning"),
        ("DocHiddenItemRef", "文档引用了隐藏项", "取消隐藏或移除引用", "Warning"),
        ("DocDuplicateAnchor", "文档锚点（anchor）重复", "修正标题层级", "Warning"),
        ("DocMacroDoc", "宏文档生成异常", "检查宏文档注释", "Warning"),
        ("DocTraitImplMissing", "trait 实现的文档缺失", "补充 impl 文档", "Warning"),
        ("DocGenericParam", "泛型参数文档未渲染", "检查泛型标注", "Warning"),
        ("DocCfgFiltered", "cfg 过滤导致文档缺失", "检查 cfg 条件", "Warning"),
        ("DocPlatformSpecific", "平台特定文档缺失", "补充平台文档", "Warning"),
        ("DocIncludeFailed", "文档 include! 文件失败", "检查包含路径", "Error"),
        ("DocEduLinkBroken", "教学文档（rust-by-example 类）链接失效", "修正链接", "Warning"),
    ]),
    ("Lint", "E72", "全阶段", "Lint（静态检查）", [
        ("LintUnusedVariable", "变量 {name} 未使用", "删除或前缀 _", "Warning"),
        ("LintUnusedImport", "导入 {name} 未使用", "移除未使用导入", "Warning"),
        ("LintUnusedFunction", "函数 {name} 未使用", "删除或 pub 导出", "Warning"),
        ("LintDeadCode", "死代码（不可达）", "移除死代码", "Warning"),
        ("LintDeprecatedUse", "使用了已废弃 API：{name}", "迁移到新 API", "Warning"),
        ("LintNonSnakeCase", "命名不符合 snake_case：{name}", "使用 snake_case", "Warning"),
        ("LintNonCamelCase", "类型命名不符合 CamelCase：{name}", "使用 CamelCase", "Warning"),
        ("LintNonUpperCaseConst", "常量命名未全大写：{name}", "使用 UPPER_CASE", "Warning"),
        ("LintHardcodedPath", "硬编码路径：{path}", "使用配置或常量", "Warning"),
        ("LintMagicNumber", "使用了魔术数字：{value}", "提取为具名常量", "Warning"),
        ("LintTodoLeft", "遗留 TODO/FIXME 注释", "完成或登记任务", "Warning"),
        ("LintPrintStatement", "使用了 print 调试语句", "改用日志", "Warning"),
        ("LintUnsafeBlock", "存在 unsafe 块（需审查）", "确认 unsafe 必要性", "Warning"),
        ("LintCloneInLoop", "在循环中不必要的 clone", "移出循环或借用", "Warning"),
        ("LintComplexity", "函数复杂度过高", "拆分函数", "Warning"),
        ("LintTooManyArgs", "函数参数过多（{n}）", "使用结构体聚合参数", "Warning"),
        ("LintDeepNesting", "嵌套层级过深", "提前返回扁平化", "Warning"),
        ("LintLineTooLong", "单行过长（{n} 字符）", "拆分长行", "Warning"),
        ("LintDocMissing", "公共项缺少文档注释", "补充文档", "Warning"),
        ("LintCopyInsteadRef", "可传引用却发生了拷贝", "改为引用传递", "Warning"),
        ("LintWildcardImport", "使用了通配导入（*）", "改为显式导入", "Warning"),
        ("LintUnreachablePattern", "match 存在不可达分支", "移除不可达分支", "Warning"),
        ("LintNonExhaustiveLet", "let-else 非穷尽", "补全处理分支", "Warning"),
        ("LintRedundantClone", "冗余的 clone 调用", "移除冗余 clone", "Warning"),
        ("LintShadowing", "变量遮蔽（shadowing）", "重命名以避免混淆", "Warning"),
        ("LintMutableNotNeeded", "变量声明为 mut 但从未修改", "移除 mut", "Warning"),
        ("LintUnnecessaryMut", "不必要的可变借用", "改为不可变借用", "Warning"),
        ("LintInefficientToStr", "低效的字符串转换", "使用更高效的格式化", "Warning"),
        ("LintPanicInProd", "生产代码中存在 panic", "改用错误返回", "Warning"),
        ("LintFloatEquality", "直接比较浮点相等", "使用容差比较", "Warning"),
        ("LintUnwrapUsed", "使用了 unwrap（可能 panic）", "使用安全的解包方式", "Warning"),
        ("LintExpectUsed", "使用了 expect（可能 panic）", "处理错误分支", "Warning"),
        ("LintIndexUnchecked", "未检查越界的索引访问", "使用 checked 访问", "Warning"),
        ("LintIteratorValue", "在迭代中持有值引用导致冲突", "调整迭代方式", "Warning"),
        ("LintLargeEnumVariant", "枚举变体过大（内存不均）", "使用 Box 装箱大字段", "Warning"),
        ("LintDerefClone", "对解引用结果多余 clone", "直接使用引用", "Warning"),
        ("LintRedundantField", "冗余的字段初始化", "移除冗余字段", "Warning"),
        ("LintNonIdiomatic", "不符合惯用写法", "采用惯用表达", "Warning"),
        ("LintStyleViolation", "代码风格违规", "运行格式化器", "Warning"),
        ("LintUnsafeSuggest", "可安全替代 unsafe 的写法", "改用安全 API", "Warning"),
        ("LintPossibleBug", "可能存在逻辑缺陷的模式", "人工复核", "Warning"),
    ]),
    ("Sec", "E73", "全阶段", "Security（安全）", [
        ("SecHardcodedSecret", "检测到硬编码密钥/口令", "改用环境变量或密钥管理", "Warning"),
        ("SecSqlInjection", "可能存在 SQL 注入风险", "使用参数化查询", "Warning"),
        ("SecCommandInjection", "可能存在命令注入风险", "校验外部输入", "Warning"),
        ("SecPathTraversal", "可能存在路径穿越（traversal）", "规范化路径并校验", "Warning"),
        ("SecUnsafeDeserialize", "不安全的反序列化", "使用受信任格式", "Warning"),
        ("SecWeakCrypto", "使用了弱加密算法：{algo}", "改用强加密", "Warning"),
        ("SecInsecureRandom", "使用了不安全随机数源", "使用密码学安全随机", "Warning"),
        ("SecTlsVerificationOff", "关闭了 TLS 证书校验", "启用证书校验", "Warning"),
        ("SecCleartextTransport", "明文传输敏感数据", "使用加密通道", "Warning"),
        ("SecUnsafeEval", "执行了不可信的动态代码", "避免动态执行", "Warning"),
        ("SecBufferOverflowRisk", "潜在的缓冲区溢出", "使用边界检查", "Warning"),
        ("SecFormatString", "格式化字符串可能受控", "使用静态格式串", "Warning"),
        ("SecIntegerOverflow", "整数溢出可能被利用", "使用饱和/检查运算", "Warning"),
        ("SecRaceCondition", "存在竞态条件风险", "使用同步保护", "Warning"),
        ("SecUseAfterFreeRisk", "潜在的释放后使用", "延长所有者生命周期", "Warning"),
        ("SecDoubleFreeRisk", "潜在的重复释放", "确保每个分配释放一次", "Warning"),
        ("SecNullDerefRisk", "潜在的空指针解引用", "使用前判空", "Warning"),
        ("SecSensitiveLog", "日志可能泄露敏感信息", "脱敏日志", "Warning"),
        ("SecInsecureTemp", "使用了可预测的临时文件名", "使用安全临时文件", "Warning"),
        ("SecSymlinkAttack", "存在符号链接攻击风险", "使用真实路径校验", "Warning"),
        ("SecUnsafeCast", "不安全的类型转换", "使用安全转换", "Warning"),
        ("SecMemoryDisclosure", "可能泄露内存内容", "清零敏感缓冲区", "Warning"),
        ("SecMissingAuthz", "缺少授权检查", "补充授权逻辑", "Warning"),
        ("SecMissingAuthn", "缺少身份认证", "补充认证逻辑", "Warning"),
        ("SecCsrfRisk", "存在 CSRF 风险", "添加令牌校验", "Warning"),
        ("SecXssRisk", "存在 XSS 风险", "转义输出", "Warning"),
        ("SecInsecureCookie", "Cookie 安全属性缺失", "设置 Secure/HttpOnly", "Warning"),
        ("SecOpenRedirect", "开放重定向风险", "校验重定向目标", "Warning"),
        ("SecUnsafeReflection", "不安全的反射/动态调用", "限制可调用集合", "Warning"),
        ("SecDependencyVuln", "依赖存在已知漏洞", "升级依赖版本", "Warning"),
        ("SecUnsafePermission", "请求了过度权限", "按最小权限原则收敛", "Warning"),
        ("SecKeySizeSmall", "密钥长度过短", "增大密钥长度", "Warning"),
        ("SecHashWeak", "使用了弱哈希（如 MD5/SHA1）", "改用 SHA-256+", "Warning"),
        ("SecCipherModeWeak", "使用了弱分组模式（如 ECB）", "改用 GCM/CBC", "Warning"),
        ("SecNonceReuse", "检测到 nonce 重用", "每次使用唯一 nonce", "Warning"),
        ("SecCertExpired", "证书已过期", "更新证书", "Warning"),
        ("SecInsecureProto", "使用了不安全协议（如 HTTP/TLS1.0）", "升级到安全协议", "Warning"),
        ("SecPrivilegeDrop", "未降权运行（以高权限常驻）", "降权到最小权限", "Warning"),
        ("SecInfoLeak", "错误信息可能泄露内部细节", "返回通用错误", "Warning"),
    ]),
    ("Conf", "E74", "全阶段", "Config（配置/Profile）", [
        ("ConfigFileNotFound", "配置文件未找到：{path}", "创建配置文件", "Error"),
        ("ConfigParseFailed", "配置解析失败：{reason}", "修正配置语法", "Error"),
        ("ConfigSchemaInvalid", "配置不符合 schema", "对照 schema 修正", "Error"),
        ("ConfigKeyUnknown", "未知配置项：{key}", "删除或更正配置项", "Error"),
        ("ConfigTypeMismatch", "配置项类型不匹配：期望 {expected}", "使用正确类型", "Error"),
        ("ConfigMissingRequired", "缺少必填配置项：{key}", "补充必填项", "Error"),
        ("ConfigDeprecated", "配置项已废弃：{key}", "迁移到新配置", "Warning"),
        ("ConfigConflict", "配置项相互冲突", "统一配置值", "Error"),
        ("ConfigEnvOverride", "环境变量覆盖配置失败", "检查环境变量名", "Warning"),
        ("ConfigProfileUnknown", "未知配置档（profile）：{profile}", "使用合法 profile", "Error"),
        ("ConfigIncludeFailed", "配置 include 失败：{path}", "检查包含路径", "Error"),
        ("ConfigCycle", "配置引用形成循环", "打破配置循环", "Error"),
        ("ConfigPermission", "配置文件无读取权限", "修正文件权限", "Error"),
        ("ConfigEncoding", "配置文件编码非法", "使用 UTF-8", "Error"),
        ("ConfigTooLarge", "配置文件过大", "拆分配置", "Warning"),
        ("ConfigValidationFailed", "配置校验失败", "检查校验规则", "Error"),
        ("ConfigDefaultInvalid", "默认值非法", "修正默认值", "Error"),
        ("ConfigRangeViolation", "配置值超出范围", "使用范围内值", "Error"),
        ("ConfigEnumInvalid", "配置枚举值非法", "使用合法枚举值", "Error"),
        ("ConfigPathInvalid", "配置路径非法：{path}", "使用合法路径", "Error"),
        ("ConfigUrlInvalid", "配置 URL 非法", "使用合法 URL", "Error"),
        ("ConfigTimeoutInvalid", "配置超时值非法", "使用合法超时", "Error"),
        ("ConfigFeatureConflict", "特性配置冲突", "统一特性开关", "Error"),
        ("ConfigTargetMismatch", "配置与目标不匹配", "检查目标配置", "Error"),
        ("ConfigRuntimeMismatch", "运行期配置与启动期不一致", "统一配置来源", "Error"),
        ("ConfigHotReloadFailed", "配置热加载失败", "检查配置变更", "Warning"),
        ("ConfigSecretLeak", "配置可能包含密钥明文", "改用密钥引用", "Warning"),
        ("ConfigFormatUnknown", "未知配置格式", "使用受支持格式", "Error"),
        ("ConfigMergeConflict", "多来源配置合并冲突", "明确合并优先级", "Error"),
        ("ConfigVersionMismatch", "配置版本不兼容", "迁移配置版本", "Error"),
        ("ConfigUnsafeValue", "配置含不安全值", "审查配置值", "Warning"),
        ("ConfigRedundant", "配置项冗余", "移除冗余项", "Warning"),
        ("ConfigDocMissing", "配置项缺少说明", "补充配置文档", "Warning"),
        ("ConfigTypeCoercion", "配置类型强制转换丢失精度", "使用精确类型", "Warning"),
        ("ConfigPlaceholder", "配置含未替换的占位符", "补全占位符", "Error"),
        ("ConfigConditional", "条件配置不满足分支", "检查条件", "Warning"),
        ("ConfigLocked", "配置被锁定不可修改", "解除锁定或新开配置", "Error"),
        ("ConfigEnvMissing", "配置依赖的环境变量缺失", "设置环境变量", "Error"),
        ("ConfigInvalidBool", "配置布尔值非法", "使用 true/false", "Error"),
        ("ConfigListEmpty", "配置列表为空（需至少一项）", "补充列表项", "Error"),
    ]),
    ("Telem", "E75", "全阶段", "Telemetry（可观测）", [
        ("TelemDisabled", "遥测被禁用", "启用遥测以采集", "Warning"),
        ("TelemInitFailed", "遥测初始化失败", "检查遥测配置", "Error"),
        ("TelemExportFailed", "遥测导出失败", "检查导出端点", "Warning"),
        ("TelemQueueFull", "遥测队列已满（丢弃数据）", "增大队列或降采样", "Warning"),
        ("TelemTimeout", "遥测上报超时", "增大超时或降频", "Warning"),
        ("TelemUnauthorized", "遥测端点鉴权失败", "检查凭证", "Error"),
        ("TelemEndpointUnreachable", "遥测端点不可达", "检查网络", "Warning"),
        ("TelemSchemaInvalid", "遥测数据 schema 非法", "修正数据格式", "Error"),
        ("TelemDropSpans", "追踪（trace）跨度被丢弃", "调整采样率", "Warning"),
        ("TelemMissingContext", "遥测缺少上下文（trace_id）", "注入上下文", "Warning"),
        ("TelemCardinality", "遥测标签基数过高", "降低标签维度", "Warning"),
        ("TelemPiiLeak", "遥测可能泄露个人数据", "脱敏遥测", "Warning"),
        ("TelemDuplicate", "重复上报遥测", "去重上报", "Warning"),
        ("TelemClockSkew", "遥测时钟偏差", "同步时钟", "Warning"),
        ("TelemBufferFlush", "遥测缓冲刷新失败", "检查存储", "Warning"),
        ("TelemOOM", "遥测占用内存过高", "限制遥测内存", "Warning"),
        ("TelemMisconfigured", "遥测配置不完整", "补全遥测配置", "Warning"),
        ("TelemVersionMismatch", "遥测协议版本不匹配", "对齐协议版本", "Error"),
        ("TelemSamplerInvalid", "采样器配置非法", "使用合法采样率", "Error"),
        ("TelemAttrTooLong", "遥测属性值过长", "截断属性", "Warning"),
        ("TelemNameInvalid", "遥测指标名非法", "使用合法命名", "Error"),
        ("TelemDropMetrics", "指标被丢弃", "检查导出管道", "Warning"),
        ("TelemLogFailed", "结构化日志导出失败", "检查日志端点", "Warning"),
        ("TelemCrashNoReport", "崩溃未生成遥测报告", "启用崩溃上报", "Warning"),
        ("TelemRateLimited", "遥测被限流", "降低上报频率", "Warning"),
        ("TelemSecretInAttr", "遥测属性含密钥", "移除敏感属性", "Warning"),
        ("TelemExportBlocked", "遥测导出被网络策略拦截", "配置网络策略", "Error"),
        ("TelemBackpressure", "遥测产生背压（backpressure）", "降采样", "Warning"),
        ("TelemSpanOrphan", "追踪跨度无父节点", "建立跨度关系", "Warning"),
        ("TelemLateArrival", "遥测迟到被丢弃", "增大等待窗口", "Warning"),
        ("TelemStorageFull", "遥测存储已满", "清理或扩容", "Warning"),
        ("TelemEncodingFailed", "遥测序列化失败", "检查数据格式", "Error"),
        ("TelemBatchFailed", "遥测批量发送失败", "重试发送", "Warning"),
        ("TelemNoCollector", "未配置遥测收集器", "配置 collector", "Warning"),
        ("TelemInconsistent", "遥测前后不一致", "统一采集逻辑", "Warning"),
        ("TelemDisabledFeature", "遥测所需特性未开启", "开启特性", "Warning"),
        ("TelemPrivacyPolicy", "遥测违反隐私策略", "调整采集范围", "Warning"),
        ("TelemAttrCountExceed", "遥测属性数量超限", "减少属性", "Warning"),
    ]),
    ("Xcompile", "E76", "后端", "CrossCompile（交叉编译）", [
        ("XcompileToolchainMissing", "交叉编译工具链缺失：{target}", "安装目标工具链", "Error"),
        ("XcompileSysrootMissing", "交叉编译 sysroot 缺失", "配置交叉 sysroot", "Error"),
        ("XcompileLinkerMissing", "交叉链接器缺失", "安装交叉链接器", "Error"),
        ("XcompileTargetLibMissing", "目标平台库缺失", "提供目标库", "Error"),
        ("XcompileAbiMismatch", "交叉编译 ABI 不匹配", "统一 ABI", "Error"),
        ("XcompileSyscallDiff", "目标系统调用号不同", "使用目标 syscall 表", "Error"),
        ("XcompileEndianDiff", "目标字节序不同", "处理字节序", "Error"),
        ("XcompilePointerWidth", "目标指针宽度不同", "调整数据类型", "Error"),
        ("XcompileFpuDiff", "目标 FPU 不同", "使用软浮点", "Error"),
        ("XcompileAtomicAbsent", "目标无原子支持", "禁用原子或 fallback", "Error"),
        ("XcompileCrtMissing", "目标 C 运行时缺失", "安装目标 CRT", "Error"),
        ("XcompileUnwindDiff", "目标展开模型不同", "使用目标展开策略", "Error"),
        ("XcompileEnvMismatch", "交叉编译环境不一致", "统一工具链", "Error"),
        ("XcompileQemuMissing", "运行交叉测试所需 QEMU 缺失", "安装 QEMU", "Error"),
        ("XcompileRunFailed", "交叉编译产物无法在模拟器运行", "检查模拟器配置", "Error"),
        ("XcompileHostDep", "依赖了宿主（host）专用功能", "改用目标可移植实现", "Error"),
        ("XcompilePathSep", "目标路径分隔符不同", "使用跨平台路径", "Error"),
        ("XcompileDlopen", "目标不支持动态加载", "改用静态链接", "Error"),
        ("XcompileTlsModel", "目标 TLS 模型不同", "使用兼容 TLS 模型", "Error"),
        ("XcompileStackProbe", "目标栈探测机制不同", "配置栈探测", "Error"),
        ("XcompileCodeModel", "目标代码模型不同", "使用目标代码模型", "Error"),
        ("XcompileArchFeature", "目标架构特性不可用", "禁用该特性", "Error"),
        ("XcompileLinkScript", "交叉链接脚本不匹配", "提供目标链接脚本", "Error"),
        ("XcompileObjFormat", "目标目标文件格式不同", "使用目标格式", "Error"),
        ("XcompileDebugFormat", "目标调试格式不同", "使用目标调试格式", "Error"),
        ("XcompileVendorLib", "目标厂商库缺失", "提供厂商 SDK", "Error"),
        ("XcompileSyscallTable", "系统调用表不匹配", "使用目标 syscall 表", "Error"),
        ("XcompileFloatAbi", "浮点 ABI 不同", "统一浮点 ABI", "Error"),
        ("XcompileAlignDiff", "目标对齐要求不同", "调整对齐", "Error"),
        ("XcompileVaList", "va_list 布局不同", "避免跨目标 va_list", "Error"),
        ("XcompileTimeT", "time_t 宽度不同", "使用固定宽度时间", "Error"),
        ("XcompileWchar", "wchar_t 宽度不同", "使用固定宽度字符", "Error"),
        ("XcompileLongDouble", "long double 布局不同", "避免依赖 long double", "Error"),
        ("XcompileUnwindLib", "展开库不匹配", "提供目标展开库", "Error"),
        ("XcompileSanitizer", "目标不支持消毒剂", "关闭 sanitizer", "Warning"),
        ("XcompileCoverage", "目标不支持覆盖率", "关闭覆盖率", "Warning"),
        ("XcompileProfile", "目标不支持性能画像", "关闭画像", "Warning"),
        ("XcompileEmulatorCrash", "模拟器崩溃", "检查模拟器/产物", "Error"),
        ("XcompileTargetJson", "目标描述（target.json）非法", "修正目标描述", "Error"),
    ]),
    ("Wasm", "E77", "后端", "WASM（WebAssembly）", [
        ("WasmTargetUnsupported", "当前不支持 WASM 目标", "启用 WASM 后端", "Error"),
        ("WasmInvalidOpcode", "WASM 非法操作码", "检查代码生成", "Error"),
        ("WasmMemoryGrowFailed", "WASM 内存增长（memory.grow）失败", "检查内存上限", "Error"),
        ("WasmTableFull", "WASM 表（table）已满", "增大表大小", "Error"),
        ("WasmFuncIndexOob", "WASM 函数索引越界", "检查函数索引", "Error"),
        ("WasmTypeMismatch", "WASM 类型不匹配", "统一函数签名", "Error"),
        ("WasmImportMissing", "WASM 导入（import）缺失：{name}", "提供导入实现", "Error"),
        ("WasmExportMissing", "WASM 导出（export）缺失", "显式导出符号", "Error"),
        ("WasmStackOverflow", "WASM 栈溢出", "减少递归深度", "Fatal"),
        ("WasmUnreachable", "WASM 执行到 unreachable", "检查逻辑", "Fatal"),
        ("WasmGasExceeded", "WASM 燃料（gas）耗尽", "优化计算量", "Error"),
        ("WasmSyscallAbsent", "WASM 系统调用未实现：{syscall}", "实现该 syscalls", "Error"),
        ("WasmBindgenFailed", "WASM 绑定（bindgen）生成失败", "检查绑定注解", "Error"),
        ("WasmAbiMismatch", "WASM ABI 不匹配", "统一 WASM ABI", "Error"),
        ("WasmJsInterop", "WASM 与 JS 互操作失败", "检查互操作层", "Error"),
        ("WasmNoThreads", "WASM 目标不支持线程", "使用单线程模型", "Error"),
        ("WasmNoSimd", "WASM 目标不支持 SIMD", "禁用 SIMD 路径", "Warning"),
        ("WasmNoException", "WASM 目标不支持异常", "使用错误码返回", "Error"),
        ("WasmSharedMemory", "WASM 共享内存（shared memory）不支持", "关闭共享内存", "Warning"),
        ("WasmTailCall", "WASM 尾调用扩展不可用", "避免尾调用", "Warning"),
        ("WasmBulkMemory", "WASM 批量内存扩展不可用", "降级实现", "Warning"),
        ("WasmReferenceTypes", "WASM 引用类型扩展不可用", "避免使用引用类型", "Warning"),
        ("WasmMultiValue", "WASM 多值返回扩展不可用", "改用输出参数", "Warning"),
        ("WasmSignExtension", "WASM 符号扩展扩展不可用", "手动实现扩展", "Warning"),
        ("WasmSatFloat", "WASM 饱和浮点扩展不可用", "手动饱和", "Warning"),
        ("WasmMutableGlobal", "WASM 可变全局不可用", "改用线性内存", "Warning"),
        ("WasmExceptionEncoding", "WASM 异常编码失败", "检查异常类型", "Error"),
        ("WasmImportTypeError", "WASM 导入类型错误", "对齐导入签名", "Error"),
        ("WasmStartFunc", "WASM start 函数非法", "修正 start 函数", "Error"),
        ("WasmDataCount", "WASM data count 段不匹配", "修正数据段", "Error"),
        ("WasmCustomSection", "WASM 自定义段（custom section）非法", "检查自定义段", "Error"),
        ("WasmNameSection", "WASM 名称段（name section）损坏", "重新生成名称段", "Warning"),
        ("WasmLinkerFailed", "WASM 链接（wasm-ld）失败", "检查链接参数", "Error"),
        ("WasmValidationFailed", "WASM 模块校验失败", "检查模块合法性", "Error"),
        ("WasmInstantiationFailed", "WASM 实例化失败", "检查导入与内存", "Error"),
        ("WasmNoStd", "WASM 目标无标准库", "使用 wasm 适配层", "Error"),
        ("WasmNoFilesystem", "WASM 目标无文件系统", "使用内存文件系统", "Error"),
        ("WasmNoNetwork", "WASM 目标无网络（除非配置）", "使用宿主网络 API", "Error"),
        ("WasmSizeLimit", "WASM 模块超过大小限制", "精简模块", "Error"),
    ]),
    ("Gpu", "E78", "后端", "GPU（并行计算）", [
        ("GpuTargetUnsupported", "当前不支持 GPU 目标", "启用 GPU 后端", "Error"),
        ("GpuKernelCompileFailed", "GPU 内核（kernel）编译失败", "检查内核代码", "Error"),
        ("GpuDeviceNotFound", "未找到 GPU 设备", "检查驱动/设备", "Error"),
        ("GpuOutOfMemory", "GPU 显存不足", "减少显存占用", "Error"),
        ("GpuIllegalAccess", "GPU 非法内存访问", "检查索引边界", "Fatal"),
        ("GpuWarpDivergence", "GPU 线程束（warp）分支发散", "减少分支发散", "Warning"),
        ("GpuSyncFailed", "GPU 同步（barrier）失败", "检查同步调用", "Error"),
        ("GpuTimeout", "GPU 内核执行超时", "减小工作量", "Error"),
        ("GpuInvalidDim", "GPU 网格/块维度非法", "使用合法维度", "Error"),
        ("GpuSharedMemExceed", "GPU 共享内存超过限制", "减少共享内存", "Error"),
        ("GpuNoDouble", "GPU 不支持双精度", "使用单精度", "Warning"),
        ("GpuUnifiedMemory", "GPU 统一内存（UVM）不可用", "显式拷贝内存", "Warning"),
        ("GpuDriverMismatch", "GPU 驱动版本不匹配", "升级驱动", "Error"),
        ("GpuContextLost", "GPU 上下文丢失", "重建上下文", "Error"),
        ("GpuStreamFailed", "GPU 流（stream）创建失败", "检查流配置", "Error"),
        ("GpuEventFailed", "GPU 事件（event）失败", "检查事件使用", "Error"),
        ("GpuCopyFailed", "GPU 主机-设备拷贝失败", "检查指针与大小", "Error"),
        ("GpuKernelArg", "GPU 内核参数不匹配", "对齐参数类型/大小", "Error"),
        ("GpuOccupancyLow", "GPU 占用率过低", "调整块大小", "Warning"),
        ("GpuRegisterSpill", "GPU 寄存器溢出到本地内存", "减少寄存器使用", "Warning"),
        ("GpuBankConflict", "GPU 共享内存 bank 冲突", "调整访问模式", "Warning"),
        ("GpuAtomicUnsupported", "GPU 不支持该原子操作", "使用替代同步", "Warning"),
        ("GpuCooperativeGroup", "GPU 协作组（cooperative group）不可用", "降级实现", "Warning"),
        ("GpuTensorCore", "GPU 张量核心（tensor core）不可用", "使用普通计算", "Warning"),
        ("GpuGraphFailed", "GPU 图（graph）捕获失败", "检查图节点", "Error"),
        ("GpuMpsUnavailable", "GPU MPS（多进程服务）不可用", "关闭 MPS", "Warning"),
        ("GpuMultiDevice", "多 GPU 设备间通信失败", "检查 NCCL/通信", "Error"),
        ("GpuPeerAccess", "GPU P2P 访问不可用", "使用主机中转", "Warning"),
        ("GpuProfilerFailed", "GPU 性能分析失败", "检查分析工具", "Warning"),
        ("GpuDebugUnsupported", "GPU 目标不支持调试", "使用 CPU 回退调试", "Warning"),
        ("GpuPrintfFailed", "GPU 内核 printf 失败", "检查 printf 缓冲", "Warning"),
        ("GpuAssertFailed", "GPU 内核断言失败", "修复内核逻辑", "Error"),
        ("GpuUnsupportedType", "GPU 不支持该数据类型", "使用受支持类型", "Error"),
        ("GpuLaunchFailed", "GPU 内核启动失败", "检查启动配置", "Error"),
        ("GpuNoHostCode", "GPU 目标缺少主机侧代码", "补充主机代码", "Error"),
        ("GpuLinkFailed", "GPU 设备代码链接失败", "检查设备链接", "Error"),
        ("GpuFatbinMissing", "GPU fatbin（多架构）缺失", "生成 fatbin", "Error"),
        ("GpuArchMismatch", "GPU 架构与编译架构不匹配", "使用目标架构编译", "Error"),
        ("GpuResourceLeak", "GPU 资源未释放", "释放 GPU 资源", "Warning"),
    ]),
]


def pascal(s: str) -> str:
    """把 key 规整为 PascalCase（去掉非字母数字，首字母大写）。"""
    parts = re.split(r"[^0-9a-zA-Z]+", s)
    out = []
    for p in parts:
        if not p:
            continue
        if p.isdigit():
            out.append(p)
        else:
            out.append(p[0].upper() + p[1:])
    return "".join(out)


def build_entries():
    """展开 CATALOG 为有序列表：每项 (code, variant, cat, sev, tpl, fix)"""
    entries = []
    for abbr, prefix, stage, display, scenarios in CATALOG:
        seen = set()
        for i, sc in enumerate(scenarios, start=1):
            key, tpl, fix, sev = sc
            vname = abbr + pascal(key)
            assert vname not in seen, f"variant name 重复: {vname}"
            seen.add(vname)
            code = f"{prefix}{i:02d}"
            entries.append((code, vname, abbr, sev, tpl, fix))
    return entries


def meta_block(entries):
    out = []
    for code, vname, cat, sev, tpl, fix in entries:
        fix_s = "None" if fix is None else f'Some(FixSuggestion(description: "{fix}"))'
        out.append(f'    m["{code}"] = ErrorMeta(code: "{code}", category: ErrorCategory.{cat}, severity: Severity.{sev},')
        out.append(f'        template: "{tpl}", fix: {fix_s})')
    return out


def enum_block(entries):
    return [f"    | {e[1]}" for e in entries]


def code_block(entries):
    return [f'            case ErrorCode.{e[1]} => "{e[0]}"' for e in entries]


def all_block(entries):
    return [f"        list.add(ErrorCode.{e[1]})" for e in entries]


def cat_enum_block():
    return [f"    | {c[0]}" for c in CATALOG]


def cat_prefix_block():
    return [f'            case ErrorCategory.{c[0]} => "{c[1]}"' for c in CATALOG]


def cat_stage_block():
    return [f'            case ErrorCategory.{c[0]} => "{c[2]}"' for c in CATALOG]


def cat_display_block():
    return [f'            case ErrorCategory.{c[0]} => "{c[3]}"' for c in CATALOG]


def insert_before(text, anchor, block_lines):
    idx = text.find(anchor)
    assert idx != -1, f"anchor not found: {anchor!r}"
    # 在 anchor 行之前插入
    pre = text[:idx].rstrip("\n")
    post = text[idx:]
    return pre + "\n" + "\n".join(block_lines) + "\n" + post


def insert_after_match_open(text, anchor_two_lines, block_lines):
    idx = text.find(anchor_two_lines)
    assert idx != -1, f"anchor not found: {anchor_two_lines!r}"
    ins_at = idx + len(anchor_two_lines)
    pre = text[:ins_at]
    post = text[ins_at:]
    return pre + "\n" + "\n".join(block_lines) + "\n" + post


def main():
    entries = build_entries()
    n = len(entries)
    print(f"[gen] 待新增错误码：{n} 个，覆盖 {len(CATALOG)} 个新类别")

    # ---- 校验唯一性 ----
    codes = [e[0] for e in entries]
    vnames = [e[1] for e in entries]
    assert len(set(codes)) == n, "错误码字符串重复！"
    assert len(set(vnames)) == n, "枚举变体名重复！"

    # ---- 读取 Diagnostics.cj ----
    with io.open(DIAG, "r", encoding="utf-8") as f:
        diag = f.read()

    # 1) enum 变体：插入到 `public static func all(): ArrayList<ErrorCode> {` 之前
    diag = insert_before(
        diag,
        "    public static func all(): ArrayList<ErrorCode> {",
        enum_block(entries),
    )
    # 2) META：插入到 `    return m` 之前
    diag = insert_before(diag, "    return m", meta_block(entries))
    # 3) code() 匹配臂：插入到 code() 的 match 体开头
    diag = insert_after_match_open(
        diag,
        '    public func code(): String {\n        match (this) {',
        code_block(entries),
    )
    # 4) all() 列表项：插入到 `        return list` 之前
    diag = insert_before(diag, "        return list", all_block(entries))
    # 5) ErrorCategory 枚举变体：插入到 `    public func codePrefix(): String {` 之前
    diag = insert_before(diag, "    public func codePrefix(): String {", cat_enum_block())
    # 6-8) ErrorCategory 三处 match：插入到各自 match 体开头
    diag = insert_after_match_open(
        diag,
        '    public func codePrefix(): String {\n        match (this) {',
        cat_prefix_block(),
    )
    diag = insert_after_match_open(
        diag,
        '    public func stage(): String {\n        match (this) {',
        cat_stage_block(),
    )
    diag = insert_after_match_open(
        diag,
        '    public func displayName(): String {\n        match (this) {',
        cat_display_block(),
    )
    with io.open(DIAG, "w", encoding="utf-8") as f:
        f.write(diag)
    print(f"[gen] Diagnostics.cj 已写入（新增 {n} 码 + {len(CATALOG)} 类别）")

    # ---- 读取测试，更新总数 ----
    with io.open(TEST, "r", encoding="utf-8") as f:
        t = f.read()
    new_total = 245 + n
    t = t.replace("@Expect(count, 253)", f"@Expect(count, {new_total})")
    # 更新注释中的数量描述（多个历史数值都有可能，统一替换）
    t = t.replace("遍历全部 253 个变体", f"遍历全部 {new_total} 个变体")
    t = t.replace("245 规范码 + 8 个向后兼容别名", f"{new_total} 规范码")
    with io.open(TEST, "w", encoding="utf-8") as f:
        f.write(t)
    print(f"[gen] ErrorCode_test.cj 总数断言 -> {new_total}")

    # ---- 生成 VS Code 映射表 ----
    os.makedirs(VSCODE_DIR, exist_ok=True)
    cat_display_map = {c[0]: c[3] for c in CATALOG}
    cat_stage_map = {c[0]: c[2] for c in CATALOG}
    cat_prefix_map = {c[0]: c[1] for c in CATALOG}
    # 既有类别（保留）
    legacy = {
        "Lexer": ("Lexer（词法分析）", "前端", "E00"),
        "Parser": ("Parser（语法分析）", "前端", "E01"),
        "Sema": ("Sema（语义分析）", "中端", "E10"),
        "Type": ("Type（类型系统）", "中端", "E20"),
        "Resolution": ("Resolution（名称解析）", "中端", "E30"),
        "Codegen": ("Codegen（代码生成）", "后端", "E40"),
        "Runtime": ("Runtime（运行时）", "运行期", "E50"),
        "System": ("System（系统/内部）", "全阶段", "E90"),
    }
    for k, v in legacy.items():
        cat_display_map.setdefault(k, v[0])
        cat_stage_map.setdefault(k, v[1])
        cat_prefix_map.setdefault(k, v[2])

    sev_to_editor = {
        "Fatal": {"severity": 1, "lsp": "Error", "actionable": True},
        "Error": {"severity": 1, "lsp": "Error", "actionable": True},
        "Warning": {"severity": 2, "lsp": "Warning", "actionable": False},
    }
    mapping = {
        "schemaVersion": "1.0.0",
        "generatedBy": "tools/gen_error_codes.py",
        "total": new_total,
        "categories": {
            k: {"display": cat_display_map[k], "stage": cat_stage_map[k], "prefix": cat_prefix_map[k]}
            for k in cat_display_map
        },
        "codes": [],
    }
    for code, vname, cat, sev, tpl, fix in entries:
        mapping["codes"].append({
            "code": code,
            "variant": vname,
            "category": cat,
            "severity": sev,
            "lspSeverity": sev_to_editor[sev]["lsp"],
            "editorSeverity": sev_to_editor[sev]["severity"],
            "actionable": sev_to_editor[sev]["actionable"],
            "template": tpl,
            "fix": fix,
        })
    # 补充既有 253 码的占位（只列前缀归属，供插件按前缀分组）
    with io.open(os.path.join(VSCODE_DIR, "diagnostics-map.json"), "w", encoding="utf-8") as f:
        json.dump(mapping, f, ensure_ascii=False, indent=2)
    print(f"[gen] vscode-extension/diagnostics-map.json 已生成（{new_total} 码）")

    # ---- 校验报告 ----
    report = []
    report.append(f"新增错误码总数: {n}")
    report.append(f"原有错误码: 253")
    report.append(f"最终错误码: {new_total}")
    report.append(f"新增类别数: {len(CATALOG)}")
    for c in CATALOG:
        report.append(f"  - {c[0]:12s} {c[1]} {c[3]:28s} 场景数={len(c[4])}")
    with io.open(os.path.join(ROOT, "scratch", "gen_report.txt"), "w", encoding="utf-8") as f:
        f.write("\n".join(report))
    print("[gen] 校验报告 -> scratch/gen_report.txt")


if __name__ == "__main__":
    main()
